external_name: example-node.itsinterchange.eu
self:                                                               # ------ General node settings ----------------
  domain_name: itsinterchange.eu
  tls_secret_name: example-node                                     # Name of the secret created with kubectl that contains the certificates and keys.
  control_channel_port: 443                                         # Specify the control channel port  for the Node
  key_store: example-node.itsinterchange.eu.p12                     # Name of key store file
  key_store_password: password                                      # Key store password
  trust_store: truststore.jks                                       # Name of trust store file
  trust_store_password: password                                    # Trust store password
  key_password: password                                            # Password for the node's private key.
  secret_mount_path: /jks/keys/                                     # Location of certificates and keys
  service_provider_port: "4141"                                     # Port of the onboarding server REST controller

                                                                    # ------ Component specific settings ----------
qpid:                                                               # Apache Qpid message broker
  image:
    repository: eu.gcr.io/nordic-way-aad182cc/qpid                  # Public container registry for Nordic Way where the docker images are located
    tag: "074e6bd"                                                  # Image tag for the Qpid-image
  expose_amqps: true                                                # Expose the AMPQS port for incoming messages.
  interchange_password: not-a-secure-password                       # Password for the user that the interchange app uses to validate messages arriving on Qpid
  admin_password: not-a-secure-password                             # Password for a Qpid administrative user
  persistence:                                                      # Configure persistence of queues in Qpid
    enabled: true
    storageClassName: standard
    size: 10Gi
  memorydump:
    enabled: true                                                   # store a memory dump on persistent disk
  java_mem: -Xmx1g -XX:MaxDirectMemorySize=3g                       # memory instructions for qpid
interchange:                                                        # Java application that validates incoming messages to Qpid
  image:
    repository: eu.gcr.io/nordic-way-aad182cc/interchangenode
    tag: "074e6bd"
  logging:                                                          # Optional: Specify the log level of the java application. This can be done for all java components.
  - logger_name: .root
    level: info
neighbour_discoverer:                                               # Java application that posts capabilities and subscriptions to discovered neighbouring interchanges.
  replicas: 1
  image:
    repository: eu.gcr.io/nordic-way-aad182cc/neighbour-discoverer
    tag: "074e6bd"
  logging:
  - logger_name: .root
    level: info
database:                                                           # Database of neighbouring interchanges
  image:
    repository: postgres
    tag: 15.1
  postgres_user: federation                                         # Database user
  postgres_password: federation                                     # Database password
  postgres_db: federation                                           # Database name
  persistence:                                                      # Persistence settings for the database.
    enabled: true
    storageClassName: standard
    size: 3Gi
  pgdata: /var/lib/postgresql/data/pgdata
message_collector:
  replicas: 1
  image:
    repository: eu.gcr.io/nordic-way-aad182cc/message-collector
    tag: "074e6bd"
message_forwarder:                                                  # Java application that forwards local messages to neighbours.
  image:
    repository: eu.gcr.io/nordic-way-aad182cc/message-forwarder
    tag: "074e6bd"
  logging:
  - logger_name: .root
    level: info
  key_store_type: PKCS12
  trust_store_type: JKS
neighbour_server:                                                   # Java application running a REST endpoints that other neighbours contact us through
  replicas: 1
  image:
    repository: eu.gcr.io/nordic-way-aad182cc/neighbour-server
    tag: "074e6bd"
  logging:
  - logger_name: .root
    level: info
routing_configurer:                                                 # Java application that uses the Qpid API to configure routing of messages
  replicas: 1
  image:
    repository: eu.gcr.io/nordic-way-aad182cc/routing-configurer
    tag: "074e6bd"
  logging:
  - logger_name: .no.vegvesen
    level: debug
onboard_server:                                                     # Java application running a REST endpoint for managing Service Providers(create, read, update, delete)
  replicas: 1
  image:
    repository: eu.gcr.io/nordic-way-aad182cc/onboard-server
    tag: "074e6bd"
  logging:
  - logger_name: .root
    level: info
secret_dev_no:
  key_store: "test"
  trust_store: "test"
static_external_ip_name:
  "my-ip-address"