## the name which will be used to address the QPID server externally
# external_name: test.nordic-way.io

interchange:
  image:
    repository: eu.gcr.io/nordic-way-aad182cc/interchangenode
    tag: latest

postgis:
  image:
    repository: eu.gcr.io/nordic-way-aad182cc/postgis
    tag: latest

qpid:
  persistence:
    enabled: false
    storageClassName: standard
    size: 10Gi

  ## whether or not to expose amqps (5671) on public internet
  ## creates a public loadbalancer for the qpid-secure service
  expose_amqps: false

  ## must provide the name of a k8s secret (in the same namespace)
  ## which includes a private key and a signed certificate.
  ## the cert must have the same CN as .Values.external_name
  # tls_secret_name: qpid-certs
  server_private_key_file: server.key
  server_certificate_file: server.crt
  ca_certificate_file: ca.crt

  ## credentials used by the interchange server(s)
  interchange_user: interchange
  interchange_password: c81b984cd23adb8bada75135ee6bb3e9

  ## admin credentials
  admin_user: qpid-admin
  admin_password: d5779aa9d01f422db0b3d1b12b916e09

  ## each user specified here will receive access to the onramp queue as well as their own queue/binding
  users: []
  # - name: king_harald
  #   binding: "where='NO'"
  # - name: king_gustaf
  #   binding: "where='SE'"

  ## if a user requires additional queues, they can be specified here
  additional_queues: []
  # - name: odin
  #   binding: "where='valhalla'"
  #   user: king_harald