self:                                                               # ------ General node settings ----------------
  control_channel_port: 443                                         # Specify the control channel port  for the Node
  message_channel_port: 5671                                        # Specify the message channel port  for the Node
  secret_mount_path: /jks/keys/                                     # Location of certificates and keys
  service_provider_port: "4141"                                     # Port of the onboarding server REST controller
  nap_provider_port: "4242"                                         # Port of the napcore server REST controller
  nap_name: "nap"                                                   # Name of the napcore user connected to the napcore server

qpid:
  replicas: 1
  persistence:
    enabled: false
    storageClassName: standard
    size: 10Gi

  memorydump:
    enabled: false

  amqps:
    port: 5671
  http_qpid_gui:
    port: 8080
  https_qpid_rest:
    port: 443

  ## credentials used by the interchange server(s)
  interchange_user: interchange

  ## admin credentials
  admin_user: qpid-admin

  ## each user specified here will receive access to the onramp queue as well as their own queue/binding
  users: []
  # - name: king_harald
  #   binding: "originatingCountry='NO'"
  # - name: king_gustaf
  #   binding: "originatingCountry='SE'"

  ## if a user requires additional queues, they can be specified here
  additional_queues: []
  # - name: odin
  #   binding: "originatingCountry='valhalla'"
  #   user: king_harald

message_collector:
  replicas: 1

neighbour_discoverer:
  replicas: 1

neighbour_server:
  replicas: 1

onboard_server:
  replicas: 1

routing_configurer:
  replicas: 1

napcore_server:
  replicas: 1
