apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-init
  template:
    metadata:
      labels:
        app: app-init
    spec:
      containers:
        - name: app
          image: import-export-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-db:5432/federation
            - name: SPRING_DATASOURCE_USERNAME
              value: federation
            - name: SPRING_DATASOURCE_PASSWORD
              value: federation
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
