services:
  import-export-service:
    build:
      context: .
      args:
        JAR_VERSION: ${JAR_VERSION}
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/federation
      SPRING_DATASOURCE_USERNAME: federation
      SPRING_DATASOURCE_PASSWORD: federation
    volumes:
      - ./exportdata:/output