apiVersion: batch/v1
kind: Job
metadata:
  name: db-export-job
spec:
  template:
    spec:
      containers:
        - name: import-export
          image: import-export-service:latest
          imagePullPolicy: Never
          env:
            - name: EXPORT_PATH
              value: /backup
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/federation
            - name: SPRING_DATASOURCE_USERNAME
              value: federation
            - name: SPRING_DATASOURCE_PASSWORD
              value: federation
          volumeMounts:
            - name: export-volume
              mountPath: /backup
      restartPolicy: Never
      volumes:
        - name: export-volume
          persistentVolumeClaim:
            claimName: db-backup-pvc
  backoffLimit: 4
