apiVersion: batch/v1
kind: Job
metadata:
  name: db-export-job
spec:
  template:
    spec:
      containers:
        - name: import-export
          image: import-export-service:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-db:5432/federation
            - name: SPRING_DATASOURCE_USERNAME
              value: federation
            - name: SPRING_DATASOURCE_PASSWORD
              value: federation
          args:
            - "/backup/db-backup.json"
          volumeMounts:
            - name: db-backup
              mountPath: /backup
      restartPolicy: Never
      volumes:
        - name: db-backup
          persistentVolumeClaim:
            claimName: db-backup-pvc-2
  backoffLimit: 4
