apiVersion: v1
kind: Pod
metadata:
  name: pvc-access
spec:
  containers:
    - name: access
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: db-backup
          mountPath: /backup
  volumes:
    - name: db-backup
      persistentVolumeClaim:
        claimName: db-backup-pvc-2
  restartPolicy: Never