apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-registry
  template:
    metadata:
      labels:
        app: local-registry
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: local-registry
spec:
  selector:
    app: local-registry
  ports:
    - port: 5000
      targetPort: 5000