{{ if .Values.admin_frontend.certmanager_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: admin-frontend-secret
type: Opaque
data:
  key_store.p12: {{ .Values.admin_keystore }}
  interchange_ca.crt.pem: {{ .Values.admin_client_ca_trust }}
{{- end}}