kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-admin-server
  annotations:
    cloud.google.com/l4-rbs: "enabled"
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: admin-server
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.static_external_ip }}
  externalTrafficPolicy: Cluster
  selector:
    app: {{ .Chart.Name }}
    component: admin-server
    release: {{ .Release.Name }}
  ports:
    - name: onboard
      port: {{ .Values.self.admin_port }}
