apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: database
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
    component: database
    release: {{ .Release.Name }}
  ports:
  - name: db
    port: 5432
    targetPort: db
