kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-database
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: database
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: database
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: database
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag}}"
        env:
        - name: POSTGRES_USER
          value: {{ .Values.database.postgres_user | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.database.postgres_password | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.database.postgres_db | quote }}
        - name: PGDATA
          value: {{ .Values.database.pgdata | quote }}
        ports:
        - name: db
          containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
      {{- if .Values.database.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-database
      {{- else }}
        emptyDir: {}
      {{- end -}}