apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.self.tls_secret_name}}
type: Opaque
data:
  {{.Values.self.key_store}}: {{ .Values.key_store }}
  {{.Values.self.trust_store}}: {{ .Values.trust_store }}
  {{.Values.self.internal_keystore}} : {{.Values.internal_keystore_contents}}
  {{.Values.self.internal_truststore}} : {{.Values.internal_truststore_contents}}
