kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-neighbour-discoverer
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: neighbour-discoverer
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: neighbour-discoverer
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: neighbour-discoverer
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: neighbour-discoverer
        image: "{{ .Values.neighbour_discoverer.image.repository }}:{{ .Values.neighbour_discoverer.image.tag }}"
        env:
        - name: POSTGRES_URI
          value: jdbc:postgresql://{{ .Release.Name }}-database:5432/federation
        - name: SERVER_NAME
          value: {{ .Values.external_name | quote }}
        - name: DOMAIN_NAME
          value: {{ .Values.self.domain_name | quote }}
        - name: CTRL_CHNL_PORT
          value: {{ .Values.self.control_channel_port | quote }}
        - name: TRUST_STORE
          value: {{ .Values.self.secret_mount_path }}{{ .Values.self.trust_store }}
        - name: TRUST_STORE_PASSWORD
          value: {{ .Values.self.trust_store_password | quote }}
        - name: KEY_STORE
          value: {{ .Values.self.secret_mount_path }}{{ .Values.self.key_store }}
        - name: KEY_STORE_PASSWORD
          value: {{ .Values.self.key_store_password | quote }}
        - name: KEY_PASSWORD
          value: {{ .Values.self.key_password | quote }}
        - name: LOG_LEVELS
          value: "{{- range .Values.neighbour_discoverer.logging -}}
                  -Dlogging.level{{ .location }}={{ .level }}{{ ` ` }}
                 {{- end }}"
        volumeMounts:
        - name: secure
          mountPath: {{ .Values.self.secret_mount_path | quote }}
        ports:
        - name: ctrl
          containerPort: {{ .Values.self.control_channel_port }}
      volumes:
      - name: secure
        secret:
          secretName: {{ required "must provide .Values.self.tls_secret_name" .Values.self.tls_secret_name }}