apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name}}--export-db
  labels:
    app: interchange
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: export-db
    release: {{ .Release.Name }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: export-db
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Release.Name }}-database:5432/{{ .Values.database.postgres_db }}
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.postgres_user}}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.postgres_password }}"