apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "export-db.fullname" .}}--pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.persistence.size }}
  storageClassName: {{ .Values.database.persistence.storageClassName }}