apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name}}--export-db
  labels:
    app: interchange
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: export-db
    release: {{ .Release.Name }}
spec:
  template:
    spec:
      containers:
        - name: import-export-service-container
          image: "{{ .Values.export_service.image.repository}}:{{ .Values.export_service.image.tag }}"
          volumeMounts:
            - mountPath: /output
              name: datadump-pvc
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Release.Name }}-database:5432/{{ .Values.database.postgres_db }}
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.postgres_user}}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.postgres_password }}"
      volumes:
        - name: datadump-pvc
          persistentVolumeClaim:
            claimName: {{.Release.Name}}-datadump-pvc