kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-haproxy
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: haproxy
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
    component: haproxy
    release: {{ .Release.Name }}
  type: LoadBalancer
  ports:
  - name: amqps
    port: {{ .Values.self.secure_message_channel_port }}
    targetPort: amqps
  - name: http-qpid-gui
    port: {{ .Values.qpid.gui_port }}
    targetPort: http-qpid-gui
  - name: https-control
    port: {{ .Values.self.control_channel_port }}
    targetPort: https-control