kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-haproxy
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: haproxy
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: haproxy
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: haproxy
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: haproxy
        image: haproxy:2.3
        ports:
        - name: amqps
          containerPort: {{ .Values.self.message_channel_port }}
        - name: http-qpid-gui
          containerPort: 8080
        - name: https-control
          containerPort: {{ .Values.self.control_channel_port }}
        - name: onboard
          containerPort: {{ .Values.self.service_provider_port }}
        volumeMounts:
        - name: config
          mountPath: /usr/local/etc/haproxy/
        readinessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: amqps
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-haproxy