kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-haproxy
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: haproxy
    release: {{ .Release.Name }}
data:
  haproxy.cfg: |
    global
        daemon
        maxconn 4096

    defaults
        mode http
        timeout connect 5000ms
        timeout client 50000ms
        timeout server 50000ms

    frontend neighbour-server-frontend
        log global
        bind *:{{ .Values.self.control_channel_port }}
        mode tcp
        default_backend neighbour-server

    frontend qpid-api-frontend
        log global
        bind *:8080
        mode http
        default_backend qpid-api

    frontend qpid-messaging-frontend
        mode tcp
        log global
        bind *:5671
        default_backend qpid-messaging

    frontend service-provider-frontent
        log global
        bind *:{{ .Values.self.service_provider_port }}
        mode tcp
        default_backend onboard-server


    backend neighbour-server
        mode tcp
        server {{ .Release.Name }}-neighbour-server {{ .Release.Name }}-neighbour-server:{{ .Values.self.control_channel_port }} maxconn 32

    backend qpid-api
        balance roundrobin
        option httpclose
        option forwardfor
        server {{ .Release.Name }}-qpid-secure {{ .Release.Name }}-qpid-secure:8080 maxconn 32

    backend qpid-messaging
        mode tcp
        server {{ .Release.Name }}-qpid-secure {{ .Release.Name }}-qpid-secure:5671 maxconn 32

    backend onboard-server
        mode tcp
        server {{ .Release.Name }}-onboard-server {{ .Release.Name }}-onboard-server:{{ .Values.self.service_provider_port }} maxconn 32
