kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-haproxy
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: haproxy
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
    component: haproxy
    release: {{ .Release.Name }}
  type: LoadBalancer
  ports:
  - name: amqps
    port: 5671
    targetPort: amqps
  - name: http-qpid-gui
    port: 8080
    targetPort: http-qpid-gui
  - name: https-control
    port: {{ .Values.self.control_channel_port }}
    targetPort: https-control
  - name: onboard
    port: {{ .Values.self.service_provider_port }}
    targetPort: onboard
  {{- if .Values.self.static_external_ip }}
  loadBalancerIP: {{ .Values.self.static_external_ip }}
  {{- end -}}
