apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: interchange-ingress
  #namespace?
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: portal.belle.stminterchange.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ixn-belle-napcore-frontend
                port:
                  number: 3000
  tls:
    - hosts:
      - portal.belle.stminterchange.com
      secretName: belle-portal-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neighbour-ingress
  #namespace?
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
    - host: belle.stminterchange.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ixn-belle-neighbour-server
                port:
                  number: {{ .Values.self.control_channel_port }}
