apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: interchange-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: portal.belle.stminterchange.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ixn-belle-napcore-frontend
                port:
                  number: 3000
