{{ if or .Values.napcore_frontend.enabled .Values.admin_frontend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-interchange-ingress
  #namespace?
  {{- if or .Values.napcore_frontend.certmanager_enabled .Values.admin_frontend.certmanager_enabled }}
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
    {{- if .Values.napcore_frontend.enabled }}
    - host: portal.{{ .Values.external_name }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-napcore-frontend
                port:
                  number: 3000
  {{- end}}
    {{- if .Values.admin_frontend.enabled}}
    - host: admin.{{ .Values.external_name }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-admin-frontend
                port:
                  number: 3000
    {{- end}}
  {{- if or .Values.napcore_frontend.certmanager_enabled .Values.admin_frontend.certmanager_enabled }}
  tls:
    {{- if and .Values.napcore_frontend.enabled .Values.napcore_frontend.certmanager_enabled }}
    - hosts:
      - portal.{{ .Values.external_name }}
      secretName: {{ .Release.Name }}-portal-cert
    {{- end}}
    {{- if and .Values.admin_frontend.enabled .Values.admin_frontend.certmanager_enabled }}
    - hosts:
      - admin.{{ .Values.external_name }}
      secretName: {{ .Release.Name }}-admin-cert
    {{- end}}
  {{- end }}
{{- end }}
