apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: interchange-ingress
  annotations:
    kubernetes.io/ingress.regional-static-ip-name: belle-external-ip # TODO externalize
spec:
  defaultBackend:
    service:
      name: ixn-belle-napcore-frontend
      port:
        number: 3000 # TODO externalize
