{{ if and .Values.napcore_frontend.enabled .Values.napcore_frontend.keycloak.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-keycloak-discovery
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}{{ .Chart.Version }}
    component: keycloak-discovery
    release: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}-keycloak-discovery
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.6.0
          args: ["start"]
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: {{ .Values.keycloak_admin_name }}
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: {{ .Values.keycloak_admin_password }}
            - name: KC_DB_URL_HOST
              value: {{ .Release.Name }}-keycloak-db
            - name: KC_DB
              value: {{ .Values.napcore_frontend.keycloak.postgres_db }}
            - name: KC_DB_PASSWORD
              value: {{ .Values.keycloak_postgres_password }}
            - name: KC_DB_USERNAME
              value: {{ .Values.keycloak_postgres_user }}
            - name: KC_HOSTNAME
              value: login.{{ .Values.external_name }}
{{- end }}