{{ if and .Values.napcore_frontend.enabled .Values.napcore_frontend.keycloak.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-keycloak-db
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: keycloak-db
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: keycloak-db
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: keycloak-db
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: keycloak-db
          image: "postgres:18.1"
          env:
            - name: POSTGRES_USER
              value: {{ .Values.keycloak_postgres_user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.keycloak_postgres_password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.napcore_frontend.keycloak.postgres_db | quote }}

          ports:
            - containerPort: 5432
              name: db
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-data
      volumes:
        - name: postgres-data
          emptyDir: {}
{{- end }}