kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-message-forwarder
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: message-forwarder
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: message-forwarder
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: message-forwarder
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: message-forwarder
        image: "{{ .Values.message_forwarder.image.repository }}:{{ .Values.message_forwarder.image.tag }}"
        env:
        - name: POSTGRES_URI
          value: jdbc:postgresql://{{ .Release.Name }}-database:5432/federation
        - name: KEY_STORE
          value: {{ .Values.self.secret_mount_path }}{{ .Values.self.key_store }}
        - name: KEY_STORE_PASSWORD
          value: {{ .Values.self.key_store_password | quote }}
        - name: KEY_STORE_TYPE
          value: {{ .Values.message_forwarder.key_store_type | quote }}
        - name: DOMAIN_NAME
          value: {{ .Values.self.domain_name | quote }}
        - name: TRUST_STORE
          value: {{ .Values.self.secret_mount_path }}{{ .Values.self.trust_store }}
        - name: TRUST_STORE_PASSWORD
          value: {{ .Values.self.trust_store_password | quote }}
        - name: TRUST_STORE_TYPE
          value: {{ .Values.message_forwarder.trust_store_type | quote }}
        - name: SERVER_NAME
          value: {{ .Values.external_name | quote }}
        - name: LOG_LEVELS
          value: "{{- range .Values.message_forwarder.logging -}}
                  -Dlogging.level{{ .logger_name }}={{ .level }}{{ ` ` }}
                  {{- end }}"
        volumeMounts:
        - name: secure
          mountPath: {{ .Values.self.secret_mount_path | quote }}
      volumes:
      - name: secure
        secret:
          secretName: {{ required "must provide .Values.self.tls_secret_name" .Values.self.tls_secret_name }}