{{ if .Values.napcore_frontend.certmanager_enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: napcore-frontend-secret
type: Opaque
data:
  key_store.p12: {{ .Values.napcore_client_keystore }}
  interchange_ca.crt.pem: {{ .Values.napcore_client_ca_trust }}
{{- end }}
