{{ if .Values.napcore_frontend.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-napcore-server
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: napcore-server
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
    component: napcore-server
    release: {{ .Release.Name }}
  ports:
  - name: napcore
    port: {{ .Values.self.nap_provider_port }}
{{- end }}
