kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-napcore-frontend
  annotations:
    cloud.google.com/l4-rbs: "enabled"
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: napcore-frontend
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.static_external_ip }}
  externalTrafficPolicy: Cluster
  selector:
    app: {{ .Chart.Name }}
    component: napcore-frontend
    release: {{ .Release.Name }}
  ports:
  - name: nap-frontend
    port: 80
    targetPort: 3000
