kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-napcore-server
  annotations:
    cloud.google.com/l4-rbs: "enabled"
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: napcore-server
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.static_external_ip }}
  externalTrafficPolicy: Cluster
  selector:
    app: {{ .Chart.Name }}
    component: napcore-server
    release: {{ .Release.Name }}
  ports:
  - name: napcore
    port: {{ .Values.self.nap_provider_port }}
