kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-neighbour-server
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: neighbour-server
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
    component: neighbour-server
    release: {{ .Release.Name }}
  ports:
  - name: https-control
    port: {{ .Values.self.control_channel_port }}
  type: NodePort
