kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-neighbour-server
  annotations:
    cloud.google.com/l4-rbs: "enabled"
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: neighbour-server
    release: {{ .Release.Name }}
spec:
  ipFamilies:
    - IPv6
  type: LoadBalancer
  loadBalancerIP: {{ .Values.static_external_ip }}
  externalTrafficPolicy: Cluster
  selector:
    app: {{ .Chart.Name }}
    component: neighbour-server
    release: {{ .Release.Name }}
  ports:
  - name: https-control
    port: {{ .Values.self.control_channel_port }}
