kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-qpid-http
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: qpid
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
    component: qpid
    release: {{ .Release.Name }}
  ports:
  - name: http-qpid-gui
    port: {{ .Values.qpid.http_qpid_gui.port }}
    targetPort: http-qpid-gui
  - name: https-qpid-rest
    port: {{ .Values.qpid.https_qpid_rest.port }}
    targetPort: https-qpid-rest
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-qpid-secure
  annotations:
    cloud.google.com/l4-rbs: "enabled"
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: qpid
    release: {{ .Release.Name }}
spec:
  ipFamilies:
    - IPv6
  type: LoadBalancer
  loadBalancerIP: {{ .Values.static_external_ip }}
  externalTrafficPolicy: Cluster
  selector:
    app: {{ .Chart.Name }}
    component: qpid
    release: {{ .Release.Name }}
  ports:
    - name: amqps
      protocol: TCP
      port: {{ .Values.qpid.amqps.port }}
