kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-qpid
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: qpid
    release: {{ .Release.Name }}
data:
  passwd: |
    {{ .Values.qpid.admin_user }}:{{ .Values.qpid.admin_password }}
    {{ .Values.qpid.interchange_user }}:{{ .Values.qpid.interchange_password }}
  groups: |
    service-providers.users={{ range .Values.qpid.users }}{{ .name }},{{ end }}
    federated-interchanges.users=
    administrators.users={{ .Values.qpid.admin_user }},{{ .Values.external_name }}
    remote-service-providers.users=
    bi-consumers.users=
  default.json: |
    {{- $userlen := len .Values.qpid.users }}
    {{- $additionallen := len .Values.qpid.additional_queues }}
    {{- $additionallen_i := sub $additionallen 1 }}
    {{- $totallen := add $userlen $additionallen }}
    {
      "type": "BDB",
      "name": "{{ .Values.external_name }}",
      "modelVersion": "7.0",
      "exchanges": [ ],
      "queues": [
        {
          "id": "0EF5AA55-E3A8-4DD6-A394-46E1F6AED77A",
          "name": "dlqueue",
          "type": "standard",
          "durable": true,
          "holdOnPublishEnabled": false,
          "messageDurability": "ALWAYS",
          "owner": null,
          "lastUpdatedBy": "interchange",
          "createdBy": "interchange"
        },
        {
          "name": "bi-queue",
          "type": "standard",
          "durable": true,
          "maximumMessageTtl": 900000,
          "ensureNondestructiveConsumers": true,
          "holdOnPublishEnabled": false,
          "owner": null
        }
      ],
      "virtualhostaccesscontrolproviders": [
        {
          "name": "default",
          "type": "RuleBased",
          "defaultResult": "DENIED",
          "rules": [
            {
              "objectType": "ALL",
              "identity": "{{ .Values.qpid.interchange_user }}",
              "operation": "ALL",
              "outcome": "ALLOW_LOG",
              "attributes": {}
            },
            {
              "objectType": "ALL",
              "identity": "administrators",
              "operation": "ALL",
              "outcome": "ALLOW_LOG",
              "attributes": {}
            },
            {
              "objectType": "VIRTUALHOST",
              "identity": "service-providers",
              "operation": "ACCESS",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "{{ .Values.external_name }}"
              }
            },
            {
              "objectType": "VIRTUALHOST",
              "identity": "bi-consumers",
              "operation": "ACCESS",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "{{ .Values.external_name }}"
              }
            },
            {
              "objectType": "VIRTUALHOST",
              "identity": "federated-interchanges",
              "operation": "ACCESS",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "{{ .Values.external_name }}"
              }
            },
            {
              "objectType": "VIRTUALHOST",
              "identity": "remote-service-providers",
              "operation": "ACCESS",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "{{ .Values.external_name }}"
              }
            },
            {
              "objectType": "QUEUE",
              "identity": "ALL",
              "operation": "CONSUME",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "bi-queue"
              }
            },
            {{- range $i, $ex := .Values.qpid.users }}
            {
              "objectType": "QUEUE",
              "identity": "{{ $ex.name }}",
              "operation": "CONSUME",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "{{ $ex.name }}"
              }
            }{{ if gt $totallen $i }},{{ end}}
            {{- end }}
            {{- range .Values.qpid.additional_queues }}
            {
              "objectType": "QUEUE",
              "identity": "{{ .user }}",
              "operation": "CONSUME",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "{{ .name }}"
              }
            },
            {{- end }}
            {
              "objectType": "ALL",
              "identity": "ALL",
              "operation": "ALL",
              "outcome": "DENY_LOG",
              "attributes": {}
            }
          ]
        }
      ]
    }