kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-qpid
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: qpid
    release: {{ .Release.Name }}
data:
  passwd: |
    {{ .Values.qpid.admin_user }}:{{ .Values.admin_password }}
  groups: |
    service-providers.users=
    federated-interchanges.users=
    administrators.users={{ .Values.qpid.admin_user }},{{ .Values.external_name }}
    remote-service-providers.users=
    bi-consumers.users=
    clients-private-channels.users=
  config.json: |
    {
      "name": "${broker.name}",
      "modelVersion": "9.0",
      "authenticationproviders": [
        {
          "name": "clientCerts",
          "type": "External"
        },
        {
          "name": "plain",
          "type": "Plain",
          "secureOnlyMechanisms": [ ],
          "users": [ {
            "name": "{{ .Values.qpid.admin_user }}",
            "type": "managed",
            "password": "{{ .Values.admin_password }}"
          } ]
        }
      ],
      "brokerloggers": [
        {
          "name": "console",
          "type": "Console",
          "lastUpdatedBy": "admin",
          "brokerloginclusionrules": [ {
            "name": "rootInclude",
            "type": "NameAndLevel",
            "durable": true,
            "level": "INFO"
          } ]
        }
      ],
      "keystores": [
        {
          "name": "default",
          "type": "FileKeyStore",
          "storeUrl": "${KEY_STORE}",
          "password": "${KEY_STORE_PASSWORD}"
        },
        {
          "name": "internal",
          "type": "FileKeyStore",
          "storeUrl": "${INTERNAL_KEY_STORE}",
          "password": "${INTERNAL_KEY_STORE_PASSWORD}"
        }
      ],
      "plugins": [
        {
          "type": "MANAGEMENT-HTTP",
          "name": "httpManagement"
        }
      ],
      "ports": [
        {
          "name": "AMQP",
          "type": "AMQP",
          "authenticationProvider": "plain",
          "port": "5672",
          "protocols": [ "AMQP_1_0" ],
          "virtualhostaliases": [
            {
              "name": "defaultAlias",
              "type": "defaultAlias"
            },
            {
              "name": "hostnameAlias",
              "type": "hostnameAlias"
            },
            {
              "name": "nameAlias",
              "type": "nameAlias"
            }
          ]
        },
        {
          "name": "AMQPS",
          "type": "AMQP",
          "authenticationProvider": "clientCerts",
          "bindingAddress": "*",
          "keyStore": "default",
          "needClientAuth": true,
          "port": "5671",
          "protocols": [ "AMQP_1_0" ],
          "transports": [
            "SSL",
            "TCP"
          ],
          "trustStores": [ "default" ],
          "wantClientAuth": false,
          "virtualhostaliases": [
            {
              "name": "defaultAlias",
              "type": "defaultAlias"
            },
            {
              "name": "hostnameAlias",
              "type": "hostnameAlias"
            },
            {
              "name": "nameAlias",
              "type": "nameAlias"
            }
          ]
        },
        {
          "name": "HTTP",
          "port": "8080",
          "authenticationProvider": "plain",
          "protocols": [ "HTTP" ]
        },
        {
          "name": "HTTPS",
          "type": "HTTP",
          "authenticationProvider": "clientCerts",
          "bindingAddress": "*",
          "port": "443",
          "trustStores": [ "default" ],
          "keyStore": "internal",
          "needClientAuth": true,
          "wantClientAuth": false,
          "transports": [
            "SSL",
            "TCP"
          ]
        }
      ],
      "truststores": [
        {
          "name": "default",
          "type": "FileTrustStore",
          "exposedAsMessageSource": false,
          "trustAnchorValidityEnforced": false,
          "storeUrl": "${TRUST_STORE}",
          "password": "${TRUST_STORE_PASSWORD}"
        }
      ],
      "virtualhostnodes": [
        {
          "name": "default",
          "type": "JSON",
          "defaultVirtualHostNode": "true",
          "virtualHostInitialConfiguration": "file:///qpid-broker-j/work/default.json"
        }
      ],
      "groupproviders": [ {
        "name": "default",
        "type": "GroupFile",
        "path": "${GROUPS_FILE}"
      } ]
    }


  default.json: |
    {
      "type": "BDB",
      "name": "{{ .Values.external_name }}",
      "modelVersion": "9.0",
      "exchanges": [ ],
      "queues": [
        {
          "id": "0EF5AA55-E3A8-4DD6-A394-46E1F6AED77A",
          "name": "dlqueue",
          "type": "standard",
          "durable": true,
          "holdOnPublishEnabled": false,
          "messageDurability": "ALWAYS",
          "owner": null,
          "lastUpdatedBy": "interchange",
          "createdBy": "interchange"
        },
        {
          "name": "bi-datex",
          "type": "standard",
          "durable": true,
          "maximumMessageTtl": 900000,
          "ensureNondestructiveConsumers": true,
          "holdOnPublishEnabled": false,
          "owner": null
        },
        {
          "name": "bi-denm",
          "type": "standard",
          "durable": true,
          "maximumMessageTtl": 900000,
          "ensureNondestructiveConsumers": true,
          "holdOnPublishEnabled": false,
          "owner": null
        },
        {
          "name": "bi-cam",
          "type": "standard",
          "durable": true,
          "maximumMessageTtl": 900000,
          "ensureNondestructiveConsumers": true,
          "holdOnPublishEnabled": false,
          "owner": null
        },
        {
          "name": "bi-ivim",
          "type": "standard",
          "durable": true,
          "maximumMessageTtl": 900000,
          "ensureNondestructiveConsumers": true,
          "holdOnPublishEnabled": false,
          "owner": null
        },
        {
          "name": "bi-mapem",
          "type": "standard",
          "durable": true,
          "maximumMessageTtl": 900000,
          "ensureNondestructiveConsumers": true,
          "holdOnPublishEnabled": false,
          "owner": null
        },
        {
          "name": "bi-spatem",
          "type": "standard",
          "durable": true,
          "maximumMessageTtl": 900000,
          "ensureNondestructiveConsumers": true,
          "holdOnPublishEnabled": false,
          "owner": null
        },
        {
          "name": "bi-ssrem",
          "type": "standard",
          "durable": true,
          "maximumMessageTtl": 900000,
          "ensureNondestructiveConsumers": true,
          "holdOnPublishEnabled": false,
          "owner": null
        },
        {
          "name": "bi-ssem",
          "type": "standard",
          "durable": true,
          "maximumMessageTtl": 900000,
          "holdOnPublishEnabled": false,
          "owner": null
        }
      ],
      "virtualhostaccesscontrolproviders": [
        {
          "name": "default",
          "type": "RuleBased",
          "defaultResult": "DENIED",
          "rules": [
            {
              "objectType": "ALL",
              "identity": "administrators",
              "operation": "ALL",
              "outcome": "ALLOW_LOG",
              "attributes": {}
            },
            {
              "objectType": "VIRTUALHOST",
              "identity": "service-providers",
              "operation": "ACCESS",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "{{ .Values.external_name }}"
              }
            },
            {
              "objectType": "VIRTUALHOST",
              "identity": "bi-consumers",
              "operation": "ACCESS",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "{{ .Values.external_name }}"
              }
            },
            {
              "objectType": "VIRTUALHOST",
              "identity": "federated-interchanges",
              "operation": "ACCESS",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "{{ .Values.external_name }}"
              }
            },
            {
              "objectType": "VIRTUALHOST",
              "identity": "remote-service-providers",
              "operation": "ACCESS",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "{{ .Values.external_name }}"
              }
            },
            {
              "objectType": "VIRTUALHOST",
              "identity": "clients-private-channels",
              "operation": "ACCESS",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "{{ .Values.external_name }}"
              }
            },
            {
              "objectType": "QUEUE",
              "identity": "bi-consumers",
              "operation": "CONSUME",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "bi-datex"
              }
            },
            {
              "objectType": "QUEUE",
              "identity": "bi-consumers",
              "operation": "CONSUME",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "bi-denm"
              }
            },
            {
              "objectType": "QUEUE",
              "identity": "bi-consumers",
              "operation": "CONSUME",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "bi-cam"
              }
            },
            {
              "objectType": "QUEUE",
              "identity": "bi-consumers",
              "operation": "CONSUME",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "bi-ivim"
              }
            },
            {
              "objectType": "QUEUE",
              "identity": "bi-consumers",
              "operation": "CONSUME",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "bi-mapem"
              }
            },
            {
              "objectType": "QUEUE",
              "identity": "bi-consumers",
              "operation": "CONSUME",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "bi-spatem"
              }
            },
            {
              "objectType": "QUEUE",
              "identity": "bi-consumers",
              "operation": "CONSUME",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "bi-ssrem"
              }
            },
            {
              "objectType": "QUEUE",
              "identity": "bi-consumers",
              "operation": "CONSUME",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "bi-ssem"
              }
            },
            {
              "objectType": "ALL",
              "identity": "ALL",
              "operation": "ALL",
              "outcome": "DENY_LOG",
              "attributes": {}
            }
          ]
        }
      ]
    }
