kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-qpid
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: qpid
    release: {{ .Release.Name }}
data:
  passwd: |
    {{ .Values.qpid.admin_user }}:{{ .Values.qpid.admin_password }}
    {{ .Values.qpid.interchange_user }}:{{ .Values.qpid.interchange_password }}
  groups: |
    service-providers.users={{ range .Values.qpid.users }}{{ .name }},{{ end }}
    federated-interchanges.users=
    administrators.users={{ .Values.qpid.admin_user }},{{ .Values.external_name }}
  default.json: |
    {{- $userlen := len .Values.qpid.users }}
    {{- $additionallen := len .Values.qpid.additional_queues }}
    {{- $additionallen_i := sub $additionallen 1 }}
    {{- $totallen := add $userlen $additionallen }}
    {
      "type": "BDB",
      "name": "{{ .Values.external_name }}",
      "modelVersion": "7.0",
      "exchanges": [
        {
          "name" : "fedEx",
          "type" : "headers",
          "durable" : true,
          "durableBindings": [
            {{- range $i, $ex := .Values.qpid.users }}
            {
              "arguments": {
                "x-filter-jms-selector": "{{ .binding }}"
              },
              "bindingKey": "binding_key",
              "destination": "{{ .name }}"
            }{{ if gt $totallen $i }},{{ end}}
            {{- end }}
            {{- range $i, $el := .Values.qpid.additional_queues }}
            {
              "arguments": {
                "x-filter-jms-selector": "{{ $el.binding }}"
              }
              "bindingKey": "binding_key",
              "destination": "{{ $el.name }}"
            }{{if lt $i $additionallen_i }},{{end}}
            {{- end }}
          ]
        },
        {
          "name": "nwEx",
          "type": "headers",
          "durable": true,
          "durableBindings": [
            {{- range $i, $ex := .Values.qpid.users }}
            {
              "arguments": {
                "x-filter-jms-selector": "{{ $ex.binding }}"
              },
              "bindingKey": "binding_key",
              "destination": "{{ $ex.name }}"
            }{{ if gt $totallen $i }},{{ end}}
            {{- end }}
            {{- range $i, $ex := .Values.qpid.additional_queues }}
            {
              "arguments": {
                "x-filter-jms-selector": "{{ $ex.binding }}"
              },
              "bindingKey": "binding_key",
              "destination": "{{ $ex.name }}"
            }{{if lt $i $additionallen_i }},{{end}}
            {{- end }}
          ]
        }
      ],
      "queues": [
        {
          "id": "0EF5AA55-E3A8-4DD6-A394-46E1F6AED77A",
          "name": "dlqueue",
          "type": "standard",
          "durable": true,
          "holdOnPublishEnabled": false,
          "messageDurability": "ALWAYS",
          "owner": null,
          "lastUpdatedBy": "interchange",
          "createdBy": "interchange"
        },
        {{- range $i, $ex := .Values.qpid.users }}
        {
          {{- if $ex.uuid }}
          "id": "{{ $ex.uuid}}",
          {{- end }}
          "name": "{{ $ex.name }}",
          "type": "standard",
          "durable": true,
          "holdOnPublishEnabled": false,
          "messageDurability": "ALWAYS",
          "owner": null,
          "lastUpdatedBy": "interchange",
          "createdBy": "interchange"
        }{{ if gt $totallen $i }},{{ end}}
        {{- end }}
        {{- range .Values.qpid.additional_queues }}
        {
          "id": "{{ .uuid}}",
          "name": "{{ .name }}",
          "type": "standard",
          "durable": true,
          "holdOnPublishEnabled": false,
          "messageDurability": "ALWAYS",
          "owner": null,
          "lastUpdatedBy": "interchange",
          "createdBy": "interchange"
        },
        {{- end }}
        {
          "id": "01A46DBE-B8A3-408D-BF32-AD8DCEF5F569",
          "name": "onramp",
          "type": "standard",
          "durable": true,
          "holdOnPublishEnabled": false,
          "messageDurability": "ALWAYS",
          "owner": null,
          "lastUpdatedBy": "interchange",
          "createdBy": "interchange"
        }
      ],
      "virtualhostaccesscontrolproviders": [
        {
          "name": "default",
          "type": "RuleBased",
          "defaultResult": "DENIED",
          "rules": [
            {
              "objectType": "ALL",
              "identity": "{{ .Values.qpid.interchange_user }}",
              "operation": "ALL",
              "outcome": "ALLOW_LOG",
              "attributes": {}
            },
            {
              "objectType": "ALL",
              "identity": "administrators",
              "operation": "ALL",
              "outcome": "ALLOW_LOG",
              "attributes": {}
            },
            {
              "objectType": "EXCHANGE",
              "identity": "service-providers",
              "operation": "PUBLISH",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "ROUTING_KEY": "onramp",
                "NAME": ""
              }
            },
            {
              "objectType": "VIRTUALHOST",
              "identity": "service-providers",
              "operation": "ACCESS",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "{{ .Values.external_name }}"
              }
            },
            {
              "objectType" : "EXCHANGE",
              "identity" : "federated-interchanges",
              "operation" : "PUBLISH",
              "outcome" : "ALLOW_LOG",
              "attributes" : {
                "NAME" : "fedEx"
              }
            },
            {
              "objectType": "VIRTUALHOST",
              "identity": "federated-interchanges",
              "operation": "ACCESS",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "{{ .Values.external_name }}"
              }
            },
            {{- range $i, $ex := .Values.qpid.users }}
            {
              "objectType": "QUEUE",
              "identity": "{{ $ex.name }}",
              "operation": "CONSUME",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "{{ $ex.name }}"
              }
            }{{ if gt $totallen $i }},{{ end}}
            {{- end }}
            {{- range .Values.qpid.additional_queues }}
            {
              "objectType": "QUEUE",
              "identity": "{{ .user }}",
              "operation": "CONSUME",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "{{ .name }}"
              }
            },
            {{- end }}
            {
              "objectType": "ALL",
              "identity": "ALL",
              "operation": "ALL",
              "outcome": "DENY_LOG",
              "attributes": {}
            }
          ]
        }
      ]
    }