kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-qpid
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: qpid
    release: {{ .Release.Name }}
data:
  passwd: |
    {{ .Values.qpid.admin_user }}:{{ .Values.qpid.admin_password }}
    {{ .Values.qpid.interchange_user }}:{{ .Values.qpid.interchange_password }}
  groups: |
    messaging-users.users={{ range .Values.qpid.users }}{{ .name }},{{ end }}
    administrators.users={{ .Values.qpid.admin_user }}
  default.json: |
    {
      "type": "BDB",
      "name": "{{ .Values.external_name }}",
      "modelVersion": "7.0",
      "exchanges": [
        {
          "name": "nwEx",
          "type": "headers",
          "durable": true,
          "durableBindings": [
            {{- range .Values.qpid.users }}
            {
              "arguments": {
                "x-filter-jms-selector": "{{ .binding }}"
              },
              "bindingKey": "binding_key",
              "destination": "{{ .name }}"
            },
            {{- end }}
            {{- range .Values.qpid.additional_queues }}
            {
              "arguments": {
                "x-filter-jms-selector": "{{ .binding }}"
              },
              "bindingKey": "binding_key",
              "destination": "{{ .name }}"
            },
            {{- end }}
            {
              "arguments": {
                "x-filter-jms-selector": "where1 LIKE '%'"
              },
              "bindingKey": "binding_key",
              "destination": "test-out"
            }
          ]
        }
      ],
      "queues": [
        {
          "id": "7C1F3C61-AA9F-4339-A8DF-C0FDB6930D45",
          "name": "test-out",
          "type": "standard",
          "durable": true,
          "holdOnPublishEnabled": false,
          "messageDurability": "ALWAYS",
          "owner": null,
          "lastUpdatedBy": "interchange",
          "createdBy": "interchange"
        },
        {
          "id": "0EF5AA55-E3A8-4DD6-A394-46E1F6AED77A",
          "name": "dlqueue",
          "type": "standard",
          "durable": true,
          "holdOnPublishEnabled": false,
          "messageDurability": "ALWAYS",
          "owner": null,
          "lastUpdatedBy": "interchange",
          "createdBy": "interchange"
        },
        {{- range .Values.qpid.users }}
        {
          "id": "{{ .uuid}}",
          "name": "{{ .name }}",
          "type": "standard",
          "durable": true,
          "holdOnPublishEnabled": false,
          "messageDurability": "ALWAYS",
          "owner": null,
          "lastUpdatedBy": "interchange",
          "createdBy": "interchange"
        },
        {{- end }}
        {{- range .Values.qpid.additional_queues }}
        {
          "id": "{{ .uuid}}",
          "name": "{{ .name }}",
          "type": "standard",
          "durable": true,
          "holdOnPublishEnabled": false,
          "messageDurability": "ALWAYS",
          "owner": null,
          "lastUpdatedBy": "interchange",
          "createdBy": "interchange"
        },
        {{- end }}
        {
          "id": "01A46DBE-B8A3-408D-BF32-AD8DCEF5F569",
          "name": "onramp",
          "type": "standard",
          "durable": true,
          "holdOnPublishEnabled": false,
          "messageDurability": "ALWAYS",
          "owner": null,
          "lastUpdatedBy": "interchange",
          "createdBy": "interchange"
        }
      ],
      "virtualhostaccesscontrolproviders": [
        {
          "name": "default",
          "type": "RuleBased",
          "defaultResult": "DENIED",
          "rules": [
            {
              "objectType": "ALL",
              "identity": "{{ .Values.qpid.interchange_user }}",
              "operation": "ALL",
              "outcome": "ALLOW_LOG",
              "attributes": {}
            },
            {
              "objectType": "EXCHANGE",
              "identity": "messaging-users",
              "operation": "PUBLISH",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "ROUTING_KEY": "onramp",
                "NAME": ""
              }
            },
            {
              "objectType": "VIRTUALHOST",
              "identity": "messaging-users",
              "operation": "ACCESS",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "{{ .Values.external_name }}"
              }
            },
            {
              "objectType": "QUEUE",
              "identity": "messaging-users",
              "operation": "CONSUME",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "test-out"
              }
            },
            {{- range .Values.qpid.users }}
            {
              "objectType": "QUEUE",
              "identity": "{{ .name }}",
              "operation": "CONSUME",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "{{ .name }}"
              }
            },
            {{- end }}
            {{- range .Values.qpid.additional_queues }}
            {
              "objectType": "QUEUE",
              "identity": "{{ .user }}",
              "operation": "CONSUME",
              "outcome": "ALLOW_LOG",
              "attributes": {
                "NAME": "{{ .name }}"
              }
            },
            {{- end }}
            {
              "objectType": "ALL",
              "identity": "ALL",
              "operation": "ALL",
              "outcome": "DENY_LOG",
              "attributes": {}
            }
          ]
        }
      ]
    }
