---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-qpid
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: qpid
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
    component: qpid
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
  - name: amqp
    port: {{ .Values.self.message_channel_port }}
    targetPort: amqp

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-qpid-secure
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: qpid
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
    component: qpid
    release: {{ .Release.Name }}
  ports:
  - name: amqps
    port: {{ .Values.self.secure_message_channel_port }}
    targetPort: amqps
  - name: http-qpid-gui
    port: {{ .Values.qpid.gui_port }}
    targetPort: http-qpid-gui