kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-routing-configurer
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: routing-configurer
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: routing-configurer
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: routing-configurer
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: routing-configurer
        image: "{{ .Values.routing_configurer.image.repository }}:{{ .Values.routing_configurer.image.tag }}"
        env:
        - name: POSTGRES_URI
          value: jdbc:postgresql://{{ .Release.Name }}-database:5432/federation
        - name: BASE_URL
          value: https://{{ .Release.Name }}-qpid-secure
        - name: SERVER_NAME
          value: {{ .Values.external_name | quote }}
        - name: TRUST_STORE
          value: {{ .Values.self.secret_mount_path }}{{ .Values.self.trust_store }}
        - name: TRUST_STORE_PASSWORD
          value: {{ .Values.self.trust_store_password | quote }}
        - name: KEY_STORE
          value: {{ .Values.self.secret_mount_path }}{{ .Values.self.key_store }}
        - name: KEY_STORE_PASSWORD
          value: {{ .Values.self.key_store_password | quote }}
        - name: KEY_PASSWORD
          value: {{ .Values.self.key_password | quote }}
        - name: LOG_LEVELS
          value: "{{- range .Values.routing_configurer.logging -}}
                 -Dlogging.level{{ .location }}={{ .level }}{{ ` ` }}
                 {{- end }}"
        volumeMounts:
        - name: secure
          mountPath: {{ .Values.self.secret_mount_path | quote }}
      volumes:
      - name: secure
        secret:
          secretName: {{ required "must provide .Values.self.tls_secret_name" .Values.self.tls_secret_name }}