version: '3'
services:

  interchangenode:
    build: ./interchangenode
    container_name: interchangenode
    hostname: interchangenode
    environment:
      AMQP_URI: amqp://qpid
      AMQP_USER: interchange
      AMQP_PASSWORD: "12345678"

  qpid:
    build: ./qpid
    container_name: qpid
    hostname: qpid
    command: dev
    ports:
    - 8081:8080
    - 5671:5671
    - 5672:5672
    volumes:
    - "./qpid/dev:/config"
    - "./tmp:/tmp"
    - "./qpid/messages:/work/qpid.test.io/messages"
    environment:
      CERTIFICATE_FILE: "/tmp/keys/server.crt"
      PRIVATE_KEY_FILE: "/tmp/keys/server.key"
      VHOST_FILE: "/config/vhost.json"
      GROUPS_FILE: "/config/groups"
      PASSWD_FILE: "/config/passwd"

  postgis:
    build: ./postgis
    environment:
    - POSTGRES_USER=geolookup
    - POSTGRES_PASSWORD=geolookup
    - POSTGRES_DB=geolookup
    container_name: postgis
    hostname: postgis
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "geolookup"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
    - "5432"

  neighbour_db:
    image: postgres:9.6
    container_name: neighbour_db
    hostname: neighbour_db
    ports:
    - 7070:5432
    environment:
      - POSTGRES_USER=neighbours
      - POSTGRES_PASSWORD=neighbours
      - POSTGRES_DB=neighbour_db

  local_db:
    image: postgres:9.6
    container_name: local
    hostname: local
    ports:
      - 7888:5432
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=local_db