version: '3'
services:

  interchangenode:
    build: ./interchangenode
    container_name: interchangenode
    hostname: interchangenode
    depends_on:
      - qpid
      - gen_keys
    environment:
      AMQP_URI: amqp://qpid
      AMQP_USER: interchange
      AMQP_PASSWORD: "12345678"

  gen_keys:
    build: ./key-gen
    container_name: key_gen
    volumes:
      - "./tmp:/tmp"
    environment:
      CA_CN: "my_ca"
      KEY_CNS: "qpid.test.io"

  qpid:
    build: ./qpid
    container_name: qpid
    hostname: qpid
    depends_on:
      - gen_keys
    ports:
    - 8081:8080
    - 5671:5671
    - 5672:5672
    volumes:
    - "./qpid/dev:/config"
    - "./tmp:/tmp"
    - "./qpid/messages:/work/qpid.test.io/messages"
    environment:
      CA_CERTIFICATE_FILE: "/tmp/keys/my_ca.crt"
      SERVER_CERTIFICATE_FILE: "/tmp/keys/qpid.test.io.crt"
      SERVER_PRIVATE_KEY_FILE: "/tmp/keys/qpid.test.io.key"
      VHOST_FILE: "/config/vhost.json"
      GROUPS_FILE: "/config/groups"
      PASSWD_FILE: "/config/passwd"

  postgis:
    build: ./postgis
    environment:
    - POSTGRES_USER=geolookup
    - POSTGRES_PASSWORD=geolookup
    - POSTGRES_DB=geolookup
    container_name: postgis
    hostname: postgis
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "geolookup"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
    - "5432"

  federation_db:
    image: postgres:9.6
    container_name: federation_db
    hostname: federation_db
    ports:
    - 7070:5432
    environment:
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - POSTGRES_DB=federation