version: '3'
services:

  interchangenode:
    build: ./interchangenode
    container_name: interchangenode
    hostname: interchangenode
    depends_on:
      - qpid
      - gen_keys
    environment:
      AMQP_URI: amqp://qpid
      AMQP_USER: interchange
      AMQP_PASSWORD: "12345678"

  gen_keys:
    build: ./key-gen
    container_name: key_gen
    volumes:
      - "./tmp:/jks"
    environment:
      CA_CN: "my_ca"
      KEY_CNS: "qpid.test.io"

  qpid:
    build: ./qpid
    container_name: qpid
    hostname: qpid
    depends_on:
      - gen_keys
    ports:
    - 8080:8080
    - 5671:5671
    - 5672:5672
    volumes:
    - "./qpid/dev:/config"
    - "./tmp:/jks"
    - "./qpid/messages:/work/qpid.test.io/messages"
    environment:
      CA_CERTIFICATE_FILE: "/jks/keys/my_ca.crt"
      SERVER_CERTIFICATE_FILE: "/jks/keys/qpid.test.io.crt"
      SERVER_PRIVATE_KEY_FILE: "/jks/keys/qpid.test.io.key"
      VHOST_FILE: /work/default/config/default.json
      STATIC_VHOST_FILE: /config/vhost.json
      GROUPS_FILE: /work/default/config/groups
      STATIC_GROUPS_FILE: /config/groups
      PASSWD_FILE: "/config/passwd"
