version: '3'
services:

  federation-build:
    build:
      dockerfile: federation-docker-files/Federation_build
      context: ./
    image: federation-build

  gen_keys:
    build: ./key-gen
    container_name: key_gen
    volumes:
      - "./tmp:/tmp"
    environment:
      CA_CN: "my_ca"
      KEY_CNS: "bouvet"


  bouvet_db:
    build:
      dockerfile: Dockerfile
      context: ./federation-it/src/test/docker/server_db
    image: bouvet_db
    container_name: bouvet_db
    ports:
      - 32777:5432
    environment:
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - POSTGRES_DB=federation

  bouvet_qpid:
    build: ./qpid
    container_name: bouvet
    hostname: bouvet
    depends_on:
      - gen_keys
    ports:
      - 8081:8080
      - 443:443
      - 5671:5671
      - 5672:5672
    volumes:
      - "./qpid/bouvet:/config"
      - "./tmp:/tmp"
      - "./qpid/messages/bouvet:/work/bouvet/messages"
    environment:
      CA_CERTIFICATE_FILE: /tmp/keys/my_ca.crt
      SERVER_CERTIFICATE_FILE: /tmp/keys/bouvet.crt
      SERVER_PRIVATE_KEY_FILE: /tmp/keys/bouvet.key
      VHOST_FILE: "/config/vhost.json"
      GROUPS_FILE: "/config/groups"
      PASSWD_FILE: "/config/passwd"

  bouvet_neighbour_server:
    build: ./neighbour-server
    container_name: bouvet_neighbour_server
    depends_on:
      - gen_keys
      - bouvet_db
      - federation-build
    ports:
      - 8090:8090
    volumes:
      - "./tmp:/tmp"
    environment:
      - POSTGRES_URI=jdbc:postgresql://bouvet_db:5432/federation
      - SERVER_NAME=bouvet

  bouvet_routing_configurer:
    build: ./routing-configurer
    container_name: bouvet_routing_configurer
    hostname: bouvet_routing_configurer
    depends_on:
      - bouvet_qpid
      - federation-build
      - gen_keys
    volumes:
      - "./tmp:/tmp"
    environment:
      - POSTGRES_URI=jdbc:postgresql://bouvet_db:5432/federation
      - BASE_URL=https://bouvet
      - VHOST_NAME=bouvet
      - TRUSTSTORE_NAME=/tmp/keys/truststore.jks
      - TRUSTSTORE_PASSWORD=password
      - KEYSTORE_NAME=/tmp/keys/bouvet.p12
      - KEYSTORE_PASSWORD=password
      - KEY_PASSWORD=password

