version: '3'
services:

  federation-build:
    build:
      dockerfile: federation-docker-files/Federation_build
      context: ./
    image: federation-build

  gen_keys:
    build: ./key-gen
    container_name: key_gen
    volumes:
      - "./tmp:/jks"
    environment:
      CA_CN: "my_ca"
      KEY_CNS: "bouvet remote kyrre"

  db:
    image: postgres:9.6
    container_name: message-forwarder-db
    ports:
      - 7080:5432
    environment:
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - POSTGRES_DB=federation

  bouvet_qpid:
    build: ./qpid
    container_name: bouvet
    hostname: bouvet
    depends_on:
      - gen_keys
    ports:
      - 5600:5671
      - 8080:8080
    volumes:
      - "./message-forwarder/src/test/docker/localIxn/config:/config"
      - "./tmp:/jks"
      - "./qpid/messages/bouvet:/work/bouvet/messages"
    environment:
      CA_CERTIFICATE_FILE: /jks/keys/my_ca.crt
      SERVER_CERTIFICATE_FILE: /jks/keys/bouvet.crt
      SERVER_PRIVATE_KEY_FILE: /jks/keys/bouvet.key
      VHOST_FILE: "/config/vhost.json"
      GROUPS_FILE: "/config/groups"
      PASSWD_FILE: "/config/passwd"

  remote_qpid:
    build: ./qpid
    container_name: remote
    hostname: remote
    depends_on:
     - gen_keys
    ports:
     - 5601:5671
     - 8081:8080
    volumes:
    - "./message-forwarder/src/test/docker/remoteIxn/config:/config"
    - "./tmp:/jks"
    - "./qpid/messages/remote:/work/remote/messages"
    environment:
      CA_CERTIFICATE_FILE: /jks/keys/my_ca.crt
      SERVER_CERTIFICATE_FILE: /jks/keys/remote.crt
      SERVER_PRIVATE_KEY_FILE: /jks/keys/remote.key
      VHOST_FILE: "/config/vhost.json"
      GROUPS_FILE: "/config/groups"
      PASSWD_FILE: "/config/passwd"

  message_forwarder_app:
    build: ./message-forwarder
    depends_on:
      - db
      - bouvet_qpid
      - remote_qpid
    volumes:
      - "./tmp:/jks"
    environment:
      POSTGRES_URI: "jdbc:postgresql://db:5432/federation"
      SERVER_NAME: "bouvet"
      KEY_STORE_FILE: "/jks/keys/bouvet.p12"
      KEY_STORE_PASSWORD: "password"
      KEY_STORE_TYPE: "PKCS12"
      TRUST_STORE_PATH: "/jks/keys/truststore.jks"
      TRUST_STORE_PASSWORD: "password"
      TRUST_STORE_TYPE: "JKS"