version: '3'
services:
  onboard_client:
    dns: 172.28.1.1
    build:
      context: ./onboard-rest-client
    volumes:
      - "./keys_sp_kyrre:/jks"
    environment:
      - ONBOARD_SERVER=https://nodea.interchange.kyrre.priv.no:8797
      - USER=kyrre
      - KEY_STORE=/jks/chain.kyrre.p12
      - KEY_STORE_PASSWORD=password
      - TRUST_STORE_PATH=/jks/truststore.jks
      - TRUST_STORE_PASSWORD=password
    networks:
      - testing_net

networks:
  testing_net:



