version: '3'
services:
  bouvet_qpid:
    build: ./qpid
    container_name: bouvet
    hostname: bouvet
    command: dev
    ports:
    - 8080
    - 443
    - 5671
    - 5672
    volumes:
    - "./message-forwarder/src/test/docker/localIxn/config:/config"
    - "./tmp:/tmp"
    - "./qpid/messages/bouvet:/work/bouvet/messages"
    environment:
      SERVER_CN: "bouvet"
      CERTIFICATE_FILE: "/tmp/keys/server.crt"
      PRIVATE_KEY_FILE: "/tmp/keys/server.key"
      VHOST_FILE: "/config/vhost.json"
      GROUPS_FILE: "/config/groups"
      PASSWD_FILE: "/config/passwd"
