version: '3'
services:

 key_gen:
    build: ./key-gen
    container_name: key_gen
    volumes:
      - "./tmp:/jks"
    environment:
      CA_CN: "ca.bouvetinterchange.eu"
      KEY_CNS: "local.bouvetinterchange.eu remote.bouvetinterchange.eu king_gustaf.bouvetinterchange.eu"
