version: '3'
services:

  federation-build:
    build:
      dockerfile: federation-docker-files/Federation_build
      context: ./
    image: federation-build

  bouvet_db:
    image: postgres:9.6
    container_name: bouvet_db
    ports:
      - 32777:5432
    environment:
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - POSTGRES_DB=federation

  bouvet_db_filler:
    build: ./test-data-helpers
    environment:
    - POSTGRES_URI=jdbc:postgresql://bouvet_db:5432/federation
    - DB_HELPER_TYPE=subscriber
    container_name: bouvet_db_filler
    hostname: bouvet_db_filler
    depends_on:
    - bouvet_db
    - federation-build

  bouvet_qpid:
    build: ./qpid
    ports:
      - 8080
      - 443
      - 5671
      - 5672
    volumes:
      - "./qpid/bouvet:/config"
      - "./tmp:/tmp"
      - "./qpid/messages/bouvet:/work/bouvet/messages"
    environment:
      - CA_CERTIFICATE_FILE=/tmp/keys/my_ca.crt
      - SERVER_CERTIFICATE_FILE=/tmp/keys/bouvet.crt
      - SERVER_PRIVATE_KEY_FILE=/tmp/keys/bouvet.key
      - VHOST_FILE=/config/vhost.json
      - GROUPS_FILE=/config/groups
      - PASSWD_FILE=/config/passwd

  bouvet_neighbour_server:
    build: ./neighbour-server
    depends_on:
      - bouvet_db
      - federation-build
    ports:
      - 8090
    volumes:
      - "./tmp:/tmp"
    environment:
      - POSTGRES_URI=jdbc:postgresql://bouvet_db:5432/federation
      - SERVER_NAME=bouvet
      - DNS_MOCK_NAMES=bouvet,remote
      - DNS_TYPE=mock

  bouvet_routing_configurer:
    build: ./routing-configurer
    depends_on:
      - federation-build
    links:
      - "bouvet_qpid:bouvet"
    volumes:
      - "./tmp:/tmp"
    environment:
      - POSTGRES_URI=jdbc:postgresql://bouvet_db:5432/federation
      - BASE_URL=https://bouvet
      - VHOST_NAME=bouvet
      - TRUSTSTORE_NAME=/tmp/keys/truststore.jks
      - TRUSTSTORE_PASSWORD=password
      - KEYSTORE_NAME=/tmp/keys/bouvet.p12
      - KEYSTORE_PASSWORD=password
      - KEY_PASSWORD=password

  bouvet_neighbour_discoverer:
    build: ./neighbour-discoverer
    depends_on:
      - bouvet_db
      - federation-build
    links:
      - "remote_neighbour_server:remote"
    volumes:
      - "./tmp:/tmp"
    environment:
      - POSTGRES_URI=jdbc:postgresql://bouvet_db:5432/federation
      - SERVER_NAME=bouvet
      - DNS_MOCK_NAMES=bouvet,remote
      - DNS_TYPE=mock

  remote_db:
    image: postgres:9.6
    container_name: remote_db
    ports:
      - 32778:5432
    environment:
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - POSTGRES_DB=federation

  remote_db_filler:
    build: ./test-data-helpers
    environment:
    - POSTGRES_URI=jdbc:postgresql://remote_db:5432/federation
    - DB_HELPER_TYPE=provider
    container_name: remote_db_filler
    hostname: remote_db_filler
    depends_on:
    - remote_db
    - federation-build

  remote_neighbour_server:
    build: ./neighbour-server
    depends_on:
      - remote_db
      - federation-build
    ports:
      - 8090
    volumes:
      - "./tmp:/tmp"
    environment:
      - POSTGRES_URI=jdbc:postgresql://remote_db:5432/federation
      - SERVER_NAME=remote
      - DNS_MOCK_NAMES=bouvet,remote
      - DNS_TYPE=mock

  remote_neighbour_discoverer:
    build: ./neighbour-discoverer
    depends_on:
      - remote_db
      - federation-build
    links:
      - "bouvet_neighbour_server:bouvet"
    volumes:
      - "./tmp:/tmp"
    environment:
      - POSTGRES_URI=jdbc:postgresql://remote_db:5432/federation
      - SERVER_NAME=remote
      - DNS_MOCK_NAMES=bouvet,remote
      - DNS_TYPE=mock

  remote_qpid:
    build: ./qpid
    ports:
      - 8080
      - 443
      - 5671
      - 5672
    volumes:
      - "./qpid/remote:/config"
      - "./tmp:/tmp"
      - "./qpid/messages/remote:/work/remote/messages"
    environment:
      - CA_CERTIFICATE_FILE=/tmp/keys/my_ca.crt
      - SERVER_CERTIFICATE_FILE=/tmp/keys/remote.crt
      - SERVER_PRIVATE_KEY_FILE=/tmp/keys/remote.key
      - VHOST_FILE=/config/vhost.json
      - GROUPS_FILE=/config/groups
      - PASSWD_FILE=/config/passwd

  remote_routing_configurer:
    build: ./routing-configurer
    depends_on:
      - federation-build
    links:
      - "remote_qpid:remote"
    volumes:
      - "./tmp:/tmp"
    environment:
      - POSTGRES_URI=jdbc:postgresql://remote_db:5432/federation
      - BASE_URL=https://remote
      - VHOST_NAME=remote
      - TRUSTSTORE_NAME=/tmp/keys/truststore.jks
      - TRUSTSTORE_PASSWORD=password
      - KEYSTORE_NAME=/tmp/keys/remote.p12
      - KEYSTORE_PASSWORD=password
      - KEY_PASSWORD=password

  bouvet_message_forwarder_app:
    build: ./message-forwarder
    depends_on:
      - bouvet_db
    volumes:
      - "./tmp:/tmp"
    environment:
      - POSTGRES_URI=jdbc:postgresql://bouvet_db:5432/federation
      - KEY_STORE_FILE=/tmp/keys/bouvet.p12
      - KEY_STORE_PASSWORD=password
      - KEY_STORE_TYPE=PKCS12
      - TRUST_STORE_PATH=/tmp/keys/truststore.jks
      - TRUST_STORE_PASSWORD=password
      - TRUST_STORE_TYPE=JKS
      - SERVER_NAME=bouvet

  remote_message_forwarder_app:
    build: ./message-forwarder
    depends_on:
      - remote_db
    volumes:
      - "./tmp:/tmp"
    environment:
      - POSTGRES_URI=jdbc:postgresql://remote_db:5432/federation
      - KEY_STORE_FILE=/tmp/keys/remote.p12
      - KEY_STORE_PASSWORD=password
      - KEY_STORE_TYPE=PKCS12
      - TRUST_STORE_PATH=/tmp/keys/truststore.jks
      - TRUST_STORE_PASSWORD=password
      - TRUST_STORE_TYPE=JKS
      - SERVER_NAME=remote
