version: '3'
services:

  federation-build:
    build:
      dockerfile: federation-docker-files/Federation_build
      context: ./
    image: federation-build

  bouvet_db:
    image: postgres:9.6
    container_name: bouvet_db
    ports:
      - 32777:5432
    environment:
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - POSTGRES_DB=federation

  bouvet_db_filler:
    build: ./test-data-helpers
    environment:
    - POSTGRES_URI=jdbc:postgresql://bouvet_db:5432/federation
    - DB_HELPER_TYPE=subscriber
    container_name: bouvet_db_filler
    hostname: bouvet_db_filler
    depends_on:
    - bouvet_db
    - federation-build

  bouvet_interchange_app:
    build: ./interchangenode
    container_name: bouvet_interchange_app
    hostname: bouvet_interchange_app
    links:
    - "bouvet_qpid:bouvet"
    environment:
      AMQP_URI: amqp://bouvet
      AMQP_USER: interchange
      AMQP_PASSWORD: "12345678"
      POSTGIS_URI: jdbc:postgresql://bouvet_postgis:5432/geolookup


  bouvet_postgis:
    build: ./postgis
    environment:
    - POSTGRES_USER=geolookup
    - POSTGRES_PASSWORD=geolookup
    - POSTGRES_DB=geolookup
    container_name: bouvet_postgis
    hostname: bouvet_postgis
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "geolookup"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
    - 8899:5432

  bouvet_qpid:
    build: ./qpid
    container_name: bouvet_qpid
    ports:
      - 8080
      - 443
      - 63002:5671
      - 5672
    volumes:
      - "./qpid/bouvet:/config"
      - "./tmp:/jks"
      - "./qpid/messages/bouvet:/work/bouvet/messages"
    environment:
      - CA_CERTIFICATE_FILE=/jks/keys/my_ca.crt
      - SERVER_CERTIFICATE_FILE=/jks/keys/bouvet.crt
      - SERVER_PRIVATE_KEY_FILE=/jks/keys/bouvet.key
      - VHOST_FILE=/config/vhost.json
      - GROUPS_FILE=/config/groups
      - PASSWD_FILE=/config/passwd

  bouvet_neighbour_server:
    build: ./neighbour-server
    container_name: bouvet_neighbour_server
    depends_on:
      - bouvet_db
      - federation-build
    ports:
      - 8090
    volumes:
      - "./tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://bouvet_db:5432/federation
      - SERVER_NAME=bouvet
      - DNS_MOCK_NAMES=bouvet,remote
      - DNS_TYPE=mock

  bouvet_routing_configurer:
    build: ./routing-configurer
    container_name: bouvet_routing_configurer
    depends_on:
      - federation-build
      - bouvet_db
    links:
      - "bouvet_qpid:bouvet"
    volumes:
      - "./tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://bouvet_db:5432/federation
      - BASE_URL=https://bouvet
      - VHOST_NAME=bouvet
      - TRUSTSTORE_NAME=/jks/keys/truststore.jks
      - TRUSTSTORE_PASSWORD=password
      - KEYSTORE_NAME=/jks/keys/bouvet.p12
      - KEYSTORE_PASSWORD=password
      - KEY_PASSWORD=password

  bouvet_neighbour_discoverer:
    build: ./neighbour-discoverer
    container_name: bouvet_neighbour_discoverer
    depends_on:
      - bouvet_db
      - federation-build
      - bouvet_db_filler
    links:
      - "remote_neighbour_server:remote"
    volumes:
      - "./tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://bouvet_db:5432/federation
      - SERVER_NAME=bouvet
      - DNS_MOCK_NAMES=bouvet,remote
      - DNS_TYPE=mock

  bouvet_message_forwarder_app:
    build: ./message-forwarder
    container_name: bouvet_message_forwarder_app
    depends_on:
    - federation-build
    - bouvet_db
    links:
    - "bouvet_qpid:bouvet"
    - "remote_qpid:remote"
    volumes:
    - "./tmp:/jks"
    environment:
    - POSTGRES_URI=jdbc:postgresql://bouvet_db:5432/federation
    - KEY_STORE_FILE=/jks/keys/bouvet.p12
    - KEY_STORE_PASSWORD=password
    - KEY_STORE_TYPE=PKCS12
    - TRUST_STORE_PATH=/jks/keys/truststore.jks
    - TRUST_STORE_PASSWORD=password
    - TRUST_STORE_TYPE=JKS
    - SERVER_NAME=bouvet

  remote_db:
    image: postgres:9.6
    container_name: remote_db
    ports:
      - 32778:5432
    environment:
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - POSTGRES_DB=federation

  remote_db_filler:
    build: ./test-data-helpers
    environment:
    - POSTGRES_URI=jdbc:postgresql://remote_db:5432/federation
    - DB_HELPER_TYPE=provider
    container_name: remote_db_filler
    hostname: remote_db_filler
    depends_on:
    - remote_db
    - federation-build

  remote_interchange_app:
    build: ./interchangenode
    container_name: remote_interchange_app
    hostname: remote_interchange_app
    links:
    - "remote_qpid:remote"
    environment:
      AMQP_URI: amqp://remote
      AMQP_USER: interchange
      AMQP_PASSWORD: "12345678"
      POSTGIS_URI: jdbc:postgresql://remote_postgis:5432/geolookup
    depends_on:
    - remote_postgis


  remote_postgis:
    build: ./postgis
    environment:
    - POSTGRES_USER=geolookup
    - POSTGRES_PASSWORD=geolookup
    - POSTGRES_DB=geolookup
    container_name: remote_postgis
    hostname: remote_postgis
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "geolookup"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
    - 6677:5432


  remote_neighbour_server:
    build: ./neighbour-server
    container_name: remote_neighbour_server
    depends_on:
      - remote_db
      - federation-build
    ports:
      - 8090
    volumes:
      - "./tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://remote_db:5432/federation
      - SERVER_NAME=remote
      - DNS_MOCK_NAMES=bouvet,remote
      - DNS_TYPE=mock

  remote_neighbour_discoverer:
    build: ./neighbour-discoverer
    container_name: remote_neighbour_discoverer
    depends_on:
      - remote_db
      - federation-build
      - remote_db_filler
    links:
      - "bouvet_neighbour_server:bouvet"
    volumes:
      - "./tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://remote_db:5432/federation
      - SERVER_NAME=remote
      - DNS_MOCK_NAMES=bouvet,remote
      - DNS_TYPE=mock

  remote_qpid:
    build: ./qpid
    container_name: remote_qpid
    ports:
      - 8080
      - 443
      - 63001:5671
      - 5672
    volumes:
      - "./qpid/remote:/config"
      - "./tmp:/jks"
      - "./qpid/messages/remote:/work/remote/messages"
    environment:
      - CA_CERTIFICATE_FILE=/jks/keys/my_ca.crt
      - SERVER_CERTIFICATE_FILE=/jks/keys/remote.crt
      - SERVER_PRIVATE_KEY_FILE=/jks/keys/remote.key
      - VHOST_FILE=/config/vhost.json
      - GROUPS_FILE=/config/groups
      - PASSWD_FILE=/config/passwd

  remote_routing_configurer:
    build: ./routing-configurer
    container_name: remote_routing_configurer
    depends_on:
      - federation-build
      - remote_db
    links:
      - "remote_qpid:remote"
    volumes:
      - "./tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://remote_db:5432/federation
      - BASE_URL=https://remote
      - VHOST_NAME=remote
      - TRUSTSTORE_NAME=/jks/keys/truststore.jks
      - TRUSTSTORE_PASSWORD=password
      - KEYSTORE_NAME=/jks/keys/remote.p12
      - KEYSTORE_PASSWORD=password
      - KEY_PASSWORD=password

  remote_message_forwarder_app:
    build: ./message-forwarder
    container_name: remote_message_forwarder_app
    depends_on:
      - federation-build
      - remote_db
    links:
      - "bouvet_qpid:bouvet"
      - "remote_qpid:remote"
    volumes:
      - "./tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://remote_db:5432/federation
      - KEY_STORE_FILE=/jks/keys/remote.p12
      - KEY_STORE_PASSWORD=password
      - KEY_STORE_TYPE=PKCS12
      - TRUST_STORE_PATH=/jks/keys/truststore.jks
      - TRUST_STORE_PASSWORD=password
      - TRUST_STORE_TYPE=JKS
      - SERVER_NAME=remote
