version: '3'
services:

 key_gen:
    build: ./key-gen
    container_name: key_gen
    volumes:
      - "./tmp:/jks"
    environment:
      CA_CN: "ca.itsinterchange.eu"
      KEY_CNS: "local.itsinterchange.eu remote.itsinterchange.eu king_gustaf.itsinterchange.eu"
