package no.vegvesen.ixn.napcore.model;

public enum CapabilityErrorCode {
    EXCEEDS_CHARACTER_LIMIT, ILLEGAL_CHARACTERS,
    INVALID_PUBLISHER_ID_FORMAT, INVALID_COUNTRY_CODE,
    INVALID_PUBLICATION_ID_PREFIX, INVALID_LONG_QUAD_TREE, INVALID_QUAD_TREE
}
