version: 2.1

executors:
  my-machine:
    machine: true

jobs:
  build:
    executor: my-machine
    steps:
      - checkout
      - run:
          name: run integration tests
          command: |
            mvn verify -PIT -Dorg.slf4j.simpleLogger.log.org.apache.maven=warn -B
  maven-deploy:
    executor: my-machine
    steps:
      - run:
          branch: federation-master
          name: Push maven build
          command: |
            mvn -s .circleci.settings.xml deploy
  docker-push:
      executor: my-machine
      steps:
      - run:
          name: Push containers
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud docker --authorize-only
            chmod +x build-push-images.sh
            ./build-push-images.sh

workflows:
  version: 2.1
  build_and_docker_push:
    jobs:
      - build
      - docker-push:
          requires:
          - build
      - maven-deploy:
          filters:
            branches:
              only:
                - federation-master
          requires:
            - docker-push
