version: 2.1

executors:
  my-machine:
    machine: true
    working_directory: ~/interchange

jobs:
  build:
    executor: my-machine
    steps:
      - checkout
      - run:
          name: run integration tests
          command: |
            mvn verify -Dorg.slf4j.simpleLogger.log.org.apache.maven=warn -B
      - persist_to_workspace:
          root: ~/interchange
          paths:
            - ./*

  maven-deploy:
    executor: my-machine
    steps:
      - attach_workspace:
          at: ~/interchange
      - run:
          branch: federation-master
          name: Push maven build
          command: |
            mvn -DskipTests=true -s .circleci.settings.xml deploy -Dorg.slf4j.simpleLogger.log.org.apache.maven=warn -B
  docker-push:
      executor: my-machine
      steps:
      - attach_workspace:
          at: ~/interchange
      - run:
          name: Push containers
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud docker --authorize-only
            chmod +x build-push-images.sh
            ./build-push-images.sh eu.gcr.io/nordic-way-aad182cc
  docker-push-svv:
      executor: my-machine
      steps:
      - attach_workspace:
          at: ~/interchange
      - run:
          name: Push containers
          command: |
            echo $SVV_GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${SVV_GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${SVV_GOOGLE_COMPUTE_ZONE}
            gcloud docker --authorize-only
            chmod +x build-push-images.sh
            ./build-push-images.sh gcr.io/nw-interchange-stm-whya

workflows:
  version: 2.1
  build_and_docker_push:
    jobs:
      - build
      - docker-push:
          requires:
          - build
      - docker-push-svv:
          requires:
          - build
      - maven-deploy:
          filters:
            branches:
              only:
                - federation-master
          requires:
            - docker-push
