version: 2.1
jobs:
  branches:
    only:
      - docker_hub_images
  build:
    docker:
      - image: maven:3.6.0-jdk-8
    steps:
      - checkout
      - run:
          name: Build the Container
          command: |
            mvn package -PPKG -Dorg.slf4j.simpleLogger.log.org.apache.maven=warn -B


