version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: run integration tests
          command: |
            mvn verify -PIT -PPKG -Dorg.slf4j.simpleLogger.log.org.apache.maven=warn -B
      - run:
          name: Push containers
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud docker --authorize-only
            chmod +x build-push-images.sh
            ./build-push-images.sh
