version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build the Container
          command: |
            mvn verify -PIT -Dorg.slf4j.simpleLogger.log.org.apache.maven=warn -B


