version: 2.1
jobs:
  build:
    docker:
      - image: maven:3.6.0-jdk-8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the Container
          command: |
            echo $DOCKER_MACHINE_NAME
            mvn verify -PIT -Dspring.datasource.url=jdbc:postgresql://${DOCKER_MACHINE_NAME}:7080/federation \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven=warn -B


