version: '3'
services:

  data-helper-build:
    build:
      dockerfile: test-data-helpers/data-helper-build
      context: ../
    image: data-helper-build

  db_helper_providing_interchange:
    build:
      dockerfile: Dockerfile
      context: .
    image: data_helper
    environment:
    - POSTGRES_URI=jdbc:postgresql://providing_db:5432/federation
    - DB_HELPER_TYPE=provider
    container_name: providing_interchange
    hostname: providing_interchange
    depends_on:
      - providing_db


  db_helper_subscribing_interchange:
    image: data_helper
    environment:
    - POSTGRES_URI=jdbc:postgresql://subscribing_db:5432/federation
    - DB_HELPER_TYPE=subscriber
    container_name: subscribing_interchange
    hostname: subscribing_interchange
    depends_on:
      - subscribing_db


  providing_db:
    image:  postgres:9.6
    container_name: providing_db
    ports:
    - 7080:5432
    environment:
    - POSTGRES_USER=federation
    - POSTGRES_PASSWORD=federation
    - POSTGRES_DB=federation


  subscribing_db:
    image:  postgres:9.6
    container_name: subscribing_db
    ports:
    - 7070:5432
    environment:
    - POSTGRES_USER=federation
    - POSTGRES_PASSWORD=federation
    - POSTGRES_DB=federation
