services:

# Note: now all the containers are on the same network - testing_net
# An idea for later would be to have two separate networks, one for each node,
# where the modules that need to communicate with each other are a part of both networks.

  mock-dns-server:
    build:
      context: ../fake-dns-server
      dockerfile: dns-dockerfile
    cap_add:
    - NET_ADMIN
    container_name: mock-dns-server
    hostname: mock-dns-server
    networks:
      testing_net:
        ipv4_address: 172.28.1.1
        aliases:
          - dns.bouvetinterchange.eu

  a-db:
    image: postgres:15.1
    container_name: a-db
    depends_on:
      - mock-dns-server
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - POSTGRES_DB=federation
    networks:
    - testing_net

  a-onboard-server:
    #image: eu.gcr.io/nordic-way-aad182cc/onboard-server-app:${BRANCH_TAG}
    build:
      context: ../onboard-server-app
    container_name: a-onboard-server
    depends_on:
      - a-db
    #ports:
    #  - 32666:8899
    volumes:
    - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://a-db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - SERVER_NAME=a.bouvetinterchange.eu
      - DOMAIN_NAME=bouvetinterchange.eu
      - SP_CHNL_PORT=8797
      - TRUST_STORE=/jks/keys/ca.a.bouvetinterchange.eu.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/jks/keys/a.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=password
    networks:
      - testing_net

        #TODO need to look over the meaning of each of these settings, and document them
  a-napcore-server:
    build:
      context: ../napcore-server-app
    container_name: a-napcore-server
    depends_on:
      - a-db
    ports:
      - 32777:8898
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://a-db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - SERVER_NAME=a-napcore-server
      - NAP_NAME=a.nap
      - DOMAIN_NAME=bouvetinterchange.eu
      - NAP_CHNL_PORT=8898
      - TRUST_STORE=/jks/keys/internal_a.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/jks/keys/a-napcore-server.p12
      - KEY_STORE_PASSWORD=password
    networks:
      - testing_net


  a-qpid:
    image: apache/qpid-broker-j:9.2.0-alpine
    hostname: a-qpid
    ports:
      - 8666:8080
      - 443
      - 63003:5671
      - 5672
    volumes:
      - "../qpid/a:/qpid-broker-j/work-override"
      - "../tmp:/jks"
    environment:
      - TRUST_STORE=/jks/keys/ca.bouvetinterchange.eu.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/jks/keys/a.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=password
      - INTERNAL_KEY_STORE=/jks/keys/a-qpid.p12
      - INTERNAL_KEY_STORE_PASSWORD=password
      - INTERNAL_TRUST_STORE=/jks/keys/internal_a.jks
      - INTERNAL_TRUST_STORE_PASSWORD=password
    depends_on:
    - mock-dns-server
    networks:
    - testing_net

  a-neighbour-server:
    #image: eu.gcr.io/nordic-way-aad182cc/neighbour-server-app:${BRANCH_TAG}
    build:
      context: ../neighbour-server-app
    container_name: a-neighbour-server
    depends_on:
      - a-db
    ports:
      - 8090
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://a-db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - SERVER_NAME=a.bouvetinterchange.eu
      - DOMAIN_NAME=bouvetinterchange.eu
      - CTRL_CHNL_PORT=8090
      - TRUST_STORE=/jks/keys/ca.bouvetinterchange.eu.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/jks/keys/a.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=password
    networks:
    - testing_net
    dns: 172.28.1.1

  a-routing-configurer:
    #image: eu.gcr.io/nordic-way-aad182cc/routing-configurer-app:${BRANCH_TAG}
    build:
      context: ../routing-configurer-app
    container_name: a-routing-configurer
    depends_on:
      - a-db
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://a-db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - BASE_URL=https://a-qpid
      - SERVER_NAME=a.bouvetinterchange.eu
      - TRUST_STORE=/jks/keys/internal_a.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/jks/keys/a_routing_configurer.p12
      - KEY_STORE_PASSWORD=password
      - COLLECTOR_USER=a_message_collector #TODO is this the correct place??
    networks:
    - testing_net

  a-neighbour-discoverer:
    #image: eu.gcr.io/nordic-way-aad182cc/neighbour-discoverer-app:${BRANCH_TAG}
    build:
      context: ../neighbour-discoverer-app
    container_name: a-neighbour-discoverer
    depends_on:
      - a-db
    links:
     - "b-neighbour-server:b.bouvetinterchange.eu"
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://a-db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - SERVER_NAME=a.bouvetinterchange.eu
      - DOMAIN_NAME=bouvetinterchange.eu
      - CTRL_CHNL_PORT=8090
      - TRUST_STORE=/jks/keys/ca.bouvetinterchange.eu.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/jks/keys/a.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=password
    dns: 172.28.1.1
    networks:
    - testing_net

  a-message-collector-app:
    #image: eu.gcr.io/nordic-way-aad182cc/message-collector-app:${BRANCH_TAG}
    build:
      context: ../message-collector-app
    container_name: a-message-collector-app
    depends_on:
    - a-db
    links:
    - "a-qpid:a.bouvetinterchange.eu"
    - "b-qpid:b.bouvetinterchange.eu"
    volumes:
    - "../tmp:/jks"
    environment:
    - POSTGRES_URI=jdbc:postgresql://a-db:5432/federation
    - POSTGRES_USER=federation
    - POSTGRES_PASSWORD=federation
    - KEY_STORE=/jks/keys/a.bouvetinterchange.eu.p12
    - KEY_STORE_PASSWORD=password
    - KEY_STORE_TYPE=PKCS12
    - TRUST_STORE=/jks/keys/ca.bouvetinterchange.eu.jks
    - TRUST_STORE_PASSWORD=password
    - TRUST_STORE_TYPE=JKS
    - SERVER_NAME=a-qpid
    - INTERNAL_KEY_STORE=/jks/keys/a_message_collector.p12
    - INTERNAL_KEY_STORE_PASSWORD=password
    - INTERNAL_KEY_STORE_TYPE=PKCS12
    - INTERNAL_KEY_STORE_ALIAS=a_message_collector
    - INTERNAL_TRUST_STORE=/jks/keys/internal_a.jks
    - INTERNAL_TRUST_STORE_PASSWORD=password
    - INTERNAL_TRUST_STORE_TYPE=JKS
    - LOCAL_IXN_PORT=5673
    networks:
    - testing_net

  b-db:
    image: postgres:9.6
    container_name: b-db
    depends_on:
    - mock-dns-server
    ports:
      - 25432:5432
    environment:
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - POSTGRES_DB=federation
    networks:
    - testing_net

  b-onboard-server:
    #image: eu.gcr.io/nordic-way-aad182cc/onboard-server-app:${BRANCH_TAG}
    build:
      context: ../onboard-server-app
    container_name: b-onboard-server
    depends_on:
    - b-db
    ports:
    - 32555:8696
    volumes:
    - "../tmp:/jks"
    environment:
    - POSTGRES_URI=jdbc:postgresql://b-db:5432/federation
    - POSTGRES_USER=federation
    - POSTGRES_PASSWORD=federation
    - SERVER_NAME=b.bouvetinterchange.eu
    - DOMAIN_NAME=bouvetinterchange.eu
    - SP_CHNL_PORT=8696
    - TRUST_STORE=/jks/keys/ca.b.bouvetinterchange.eu.jks
    - TRUST_STORE_PASSWORD=password
    - KEY_STORE=/jks/keys/b.bouvetinterchange.eu.p12
    - KEY_STORE_PASSWORD=password
    networks:
    - testing_net

  b-neighbour-server:
    #image: eu.gcr.io/nordic-way-aad182cc/neighbour-server-app:${BRANCH_TAG}
    build:
      context: ../neighbour-server-app
    container_name: b-neighbour-server
    depends_on:
      - b-db
    ports:
      - 8090
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://b-db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - SERVER_NAME=b.bouvetinterchange.eu
      - DOMAIN_NAME=bouvetinterchange.eu
      - CTRL_CHNL_PORT=8090
      - TRUST_STORE=/jks/keys/ca.bouvetinterchange.eu.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/jks/keys/b.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=password
    networks:
      - testing_net
    dns: 172.28.1.1

  b-neighbour-discoverer:
    #image: eu.gcr.io/nordic-way-aad182cc/neighbour-discoverer-app:${BRANCH_TAG}
    build:
      context: ../neighbour-discoverer-app
    container_name: b-neighbour-discoverer
    depends_on:
      - b-db
    links:
      - "a-neighbour-server:a.bouvetinterchange.eu"
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://b-db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - SERVER_NAME=b.bouvetinterchange.eu
      #- NODE_PROVIDER_NAME=b.bouvetinterchange.eu # "my name"
      - DOMAIN_NAME=bouvetinterchange.eu
      - CTRL_CHNL_PORT=8090
      - TRUST_STORE=/jks/keys/ca.bouvetinterchange.eu.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/jks/keys/b.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=password
    networks:
    - testing_net
    dns: 172.28.1.1

  b-qpid:
    image: apache/qpid-broker-j:9.2.0-alpine
    hostname: b-qpid
    ports:
      - 8555:8080
      - 443
      - 63001:5671
      - 5672
    volumes:
      - "../qpid/b:/qpid-broker-j/work-override"
      - "../tmp:/jks"
    environment:
      - TRUST_STORE=/jks/keys/ca.bouvetinterchange.eu.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/jks/keys/b.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=password
      - INTERNAL_KEY_STORE=/jks/keys/b-qpid.p12
      - INTERNAL_KEY_STORE_PASSWORD=password
      - INTERNAL_TRUST_STORE=/jks/keys/internal_b.jks
      - INTERNAL_TRUST_STORE_PASSWORD=password
    depends_on:
    - mock-dns-server
    networks:
    - testing_net

  b-routing-configurer:
    #image: eu.gcr.io/nordic-way-aad182cc/routing-configurer-app:${BRANCH_TAG}
    build:
      context: ../routing-configurer-app
    container_name: b-routing-configurer
    depends_on:
      - b-db
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://b-db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - BASE_URL=https://b-qpid
      - SERVER_NAME=b.bouvetinterchange.eu
      - TRUST_STORE=/jks/keys/internal_b.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/jks/keys/b_routing_configurer.p12
      - KEY_STORE_PASSWORD=password
      - COLLECTOR_USER=b_message_collector
    networks:
    - testing_net

  b-message-collector-app:
    #image: eu.gcr.io/nordic-way-aad182cc/message-collector-app:${BRANCH_TAG}
    build:
      context: ../message-collector-app
    container_name: b-message-collector-app
    depends_on:
      - b-db
    links:
      - "a-qpid:a.bouvetinterchange.eu"
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://b-db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - KEY_STORE=/jks/keys/b.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=password
      - KEY_STORE_TYPE=PKCS12
      - TRUST_STORE=/jks/keys/ca.bouvetinterchange.eu.jks
      - TRUST_STORE_PASSWORD=password
      - TRUST_STORE_TYPE=JKS
      - INTERNAL_KEY_STORE=/jks/keys/b_message_collector.p12
      - INTERNAL_KEY_STORE_PASSWORD=password
      - INTERNAL_KEY_STORE_TYPE=PKCS12
      - INTERNAL_KEY_STORE_ALIAS=b_message_collector
      - INTERNAL_TRUST_STORE=/jks/keys/internal_b.jks
      - INTERNAL_TRUST_STORE_PASSWORD=password
      - INTERNAL_TRUST_STORE_TYPE=JKS
      - SERVER_NAME=b-qpid
      - LOCAL_IXN_PORT=5673
    networks:
    - testing_net

networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.28.0.0/16

