services:
  a-napcore-client:
    build:
      context: ../frontend
    depends_on:
      - a-napcore-server
    ports:
      - 3000:3000
    volumes:
      - "systemtest-keys-volume:/app/keys"
    environment:
      - PFX_KEY_FILENAME=/keys/nap.a.bouvetinterchange.eu.p12
      - PFX_PASSPHRASE=password
      - INTERCHANGE_URI=https://a-napcore-server:8898/nap/
      - INTERCHANGE_PREFIX=a.bouvetinterchange.eu.nap.
      - NEXTAUTH_SECRET=supersecret
      - NEXTAUTH_URL=http://localhost:3000
      - USE_KEYCLOAK=true
      - KEYCLOAK_CLIENT_ID=a.bouvetinterchange.eu
      - INTERNAL_KEYCLOAK_URL=http://a-keycloak:8080
      - KEYCLOAK_REALM=a.bouvetinterchange.eu
      - KEYCLOAK_CLIENT_SECRET=anothersupersecret
      - EXTERNAL_KEYCLOAK_URL=http://localhost:8888
    networks:
      - testing_net

  a-keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    ports:
      - 8888:8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./a.bouvetinterchange.eu-realm.json:/opt/keycloak/data/import/a.bouvetinterchange.eu-realm.json:ro
    command: [ "start-dev", "--import-realm" ]
    networks:
      - testing_net

