version: '3'
services:

# Note: now all the containers are on the same network - testing_net
# An idea for later would be to have two separate networks, one for each node,
# where the modules that need to communicate with each other are a part of both networks.

  mock-dns-server:
    build:
      context: ../fake-dns-server
      dockerfile: dns-dockerfile
    cap_add:
    - NET_ADMIN
    container_name: mock-dns-server
    hostname: mock-dns-server
    networks:
      testing_net:
        ipv4_address: 172.28.1.1
        aliases:
          - dns.bouvetinterchange.eu

  a_db:
    image: postgres:15.1
    container_name: a_db
    depends_on:
      - mock-dns-server
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - POSTGRES_DB=federation
    networks:
    - testing_net

  a_onboard_server:
    #image: eu.gcr.io/nordic-way-aad182cc/onboard-server-app:${BRANCH_TAG}
    build:
      context: ../onboard-server-app
    container_name: a_onboard_server
    depends_on:
      - a_db
    ports:
      - 32666:8797
    volumes:
    - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://a_db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - SERVER_NAME=a.bouvetinterchange.eu
      - DOMAIN_NAME=bouvetinterchange.eu
      - SP_CHNL_PORT=8797
      - TRUST_STORE=/jks/keys/ca.bouvetinterchange.eu.jks
      - TRUST_STORE_PASSWORD=ma9+jz78gHHy
      - KEY_STORE=/jks/keys/a.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=Sw405VRAvGt2
    networks:
      - testing_net

        #TODO need to look over the meaning of each of these settings, and document them
  a_napcore_server:
    build:
      context: ../napcore-server-app
    container_name: a_napcore_server
    depends_on:
      - a_db
    ports:
      - 32777:8898
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://a_db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - SERVER_NAME=a.bouvetinterchange.eu
      - NAP_NAME=nap.bouvetinterchange.eu #a.nap.bouvetinterchange.eu?
      - DOMAIN_NAME=bouvetinterchange.eu
      - NAP_CHNL_PORT=8898
      - TRUST_STORE=/jks/keys/internal_a.jks
      - TRUST_STORE_PASSWORD=gQmJ5mQu83Pt
      - KEY_STORE=/jks/keys/a.nap.p12
      - KEY_STORE_PASSWORD=CBcdd4tORiYP
    networks:
      - testing_net

  a_qpid:
    build:
      context: ../qpid
    hostname: a_qpid
    ports:
      - 8666:8080
      - 443
      - 63003:5671
      - 5672
    volumes:
      - "../qpid/a:/config"
      - "../tmp:/jks"
      - "../qpid/messages/a:/work/a/messages"
      - "../tmp/dump:/dump"
    environment:
      - TRUST_STORE=/jks/keys/ca.bouvetinterchange.eu.jks
      - TRUST_STORE_PASSWORD=ma9+jz78gHHy
      - KEY_STORE=/jks/keys/a.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=Sw405VRAvGt2
      - VHOST_FILE=/work/default/config/default.json
      - STATIC_VHOST_FILE=/config/vhost.json
      - GROUPS_FILE=/work/default/config/groups
      - STATIC_GROUPS_FILE=/config/groups
      - PASSWD_FILE=/config/passwd
      - JAVA_OPTS=-XX:HeapDumpPath=/dump/
        #internal trust store?
      - INTERNAL_KEY_STORE=/jks/keys/a_qpid.p12
      - INTERNAL_KEY_STORE_PASSWORD=Bwucl72IdLGn
      - INTERNAL_TRUST_STORE=/jks/keys/internal_a.jks
      - INTERNAL_TRUST_STORE_PASSWORD=gQmJ5mQu83Pt
    depends_on:
    - mock-dns-server
    networks:
    - testing_net

  a_neighbour_server:
    #image: eu.gcr.io/nordic-way-aad182cc/neighbour-server-app:${BRANCH_TAG}
    build:
      context: ../neighbour-server-app
    container_name: a_neighbour_server
    depends_on:
      - a_db
    ports:
      - 8090
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://a_db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - SERVER_NAME=a.bouvetinterchange.eu
      - DOMAIN_NAME=bouvetinterchange.eu
      - CTRL_CHNL_PORT=8090
      - TRUST_STORE=/jks/keys/ca.bouvetinterchange.eu.jks
      - TRUST_STORE_PASSWORD=ma9+jz78gHHy
      - KEY_STORE=/jks/keys/a.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=Sw405VRAvGt2
    networks:
    - testing_net
    dns: 172.28.1.1

  a_routing_configurer:
    #image: eu.gcr.io/nordic-way-aad182cc/routing-configurer-app:${BRANCH_TAG}
    build:
      context: ../routing-configurer-app
    container_name: a_routing_configurer
    depends_on:
      - a_db
        #links:
        #- "a_qpid:a.bouvetinterchange.eu"
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://a_db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - BASE_URL=https://a_qpid
      - SERVER_NAME=a.bouvetinterchange.eu
      - TRUST_STORE=/jks/keys/internal_a.jks
      - TRUST_STORE_PASSWORD=gQmJ5mQu83Pt
      - KEY_STORE=/jks/keys/a_routing_configurer.p12
      - KEY_STORE_PASSWORD=hkgHDNdsf79g
    networks:
    - testing_net

  a_neighbour_discoverer:
    #image: eu.gcr.io/nordic-way-aad182cc/neighbour-discoverer-app:${BRANCH_TAG}
    build:
      context: ../neighbour-discoverer-app
    container_name: a_neighbour_discoverer
    depends_on:
      - a_db
    links:
     - "b_neighbour_server:b.bouvetinterchange.eu"
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://a_db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - SERVER_NAME=a.bouvetinterchange.eu
      - DOMAIN_NAME=bouvetinterchange.eu
      - CTRL_CHNL_PORT=8090
      - TRUST_STORE=/jks/keys/ca.bouvetinterchange.eu.jks
      - TRUST_STORE_PASSWORD=ma9+jz78gHHy
      - KEY_STORE=/jks/keys/a.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=Sw405VRAvGt2
    dns: 172.28.1.1
    networks:
    - testing_net

  a_message_collector_app:
    #image: eu.gcr.io/nordic-way-aad182cc/message-collector-app:${BRANCH_TAG}
    build:
      context: ../message-collector-app
    container_name: a_message_collector_app
    depends_on:
    - a_db
    links:
    - "a_qpid:a.bouvetinterchange.eu"
    - "b_qpid:b.bouvetinterchange.eu"
    volumes:
    - "../tmp:/jks"
    environment:
    - POSTGRES_URI=jdbc:postgresql://a_db:5432/federation
    - POSTGRES_USER=federation
    - POSTGRES_PASSWORD=federation
    - KEY_STORE=/jks/keys/a.bouvetinterchange.eu.p12
    - KEY_STORE_PASSWORD=Sw405VRAvGt2
    - KEY_STORE_TYPE=PKCS12
    - TRUST_STORE=/jks/keys/ca.bouvetinterchange.eu.jks
    - TRUST_STORE_PASSWORD=ma9+jz78gHHy
    - TRUST_STORE_TYPE=JKS
    - SERVER_NAME=a.bouvetinterchange.eu
    networks:
    - testing_net

  b_db:
    image: postgres:9.6
    container_name: b_db
    depends_on:
    - mock-dns-server
    ports:
      - 25432:5432
    environment:
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - POSTGRES_DB=federation
    networks:
    - testing_net

  b_onboard_server:
    #image: eu.gcr.io/nordic-way-aad182cc/onboard-server-app:${BRANCH_TAG}
    build:
      context: ../onboard-server-app
    container_name: b_onboard_server
    depends_on:
    - b_db
    ports:
    - 32555:8696
    volumes:
    - "../tmp:/jks"
    environment:
    - POSTGRES_URI=jdbc:postgresql://b_db:5432/federation
    - POSTGRES_USER=federation
    - POSTGRES_PASSWORD=federation
    - SERVER_NAME=b.bouvetinterchange.eu
    - DOMAIN_NAME=bouvetinterchange.eu
    - SP_CHNL_PORT=8696
    - TRUST_STORE=/jks/keys/ca.bouvetinterchange.eu.jks
    - TRUST_STORE_PASSWORD=ma9+jz78gHHy
    - KEY_STORE=/jks/keys/b.bouvetinterchange.eu.p12
    - KEY_STORE_PASSWORD=FbLeD3NzofRw
    networks:
    - testing_net

  b_neighbour_server:
    #image: eu.gcr.io/nordic-way-aad182cc/neighbour-server-app:${BRANCH_TAG}
    build:
      context: ../neighbour-server-app
    container_name: b_neighbour_server
    depends_on:
      - b_db
    ports:
      - 8090
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://b_db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - SERVER_NAME=b.bouvetinterchange.eu
      - DOMAIN_NAME=bouvetinterchange.eu
      - CTRL_CHNL_PORT=8090
      - TRUST_STORE=/jks/keys/ca.bouvetinterchange.eu.jks
      - TRUST_STORE_PASSWORD=ma9+jz78gHHy
      - KEY_STORE=/jks/keys/b.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=FbLeD3NzofRw
    networks:
      - testing_net
    dns: 172.28.1.1

  b_neighbour_discoverer:
    #image: eu.gcr.io/nordic-way-aad182cc/neighbour-discoverer-app:${BRANCH_TAG}
    build:
      context: ../neighbour-discoverer-app
    container_name: b_neighbour_discoverer
    depends_on:
      - b_db
    links:
      - "a_neighbour_server:a.bouvetinterchange.eu"
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://b_db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - SERVER_NAME=b.bouvetinterchange.eu
      #- NODE_PROVIDER_NAME=b.bouvetinterchange.eu # "my name"
      - DOMAIN_NAME=bouvetinterchange.eu
      - CTRL_CHNL_PORT=8090
      - TRUST_STORE=/jks/keys/ca.bouvetinterchange.eu.jks
      - TRUST_STORE_PASSWORD=ma9+jz78gHHy
      - KEY_STORE=/jks/keys/b.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=FbLeD3NzofRw
    networks:
    - testing_net
    dns: 172.28.1.1

  b_qpid:
    build:
      context: ../qpid
    hostname: b_qpid
    ports:
      - 8555:8080
      - 443
      - 63001:5671
      - 5672
    volumes:
      - "../qpid/b:/config"
      - "../tmp:/jks"
      - "../qpid/messages/b:/work/b/messages"
    environment:
      - TRUST_STORE=/jks/keys/ca.bouvetinterchange.eu.jks
      - TRUST_STORE_PASSWORD=ma9+jz78gHHy
      - KEY_STORE=/jks/keys/b.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=FbLeD3NzofRw
      - VHOST_FILE=/work/default/config/default.json
      - STATIC_VHOST_FILE=/config/vhost.json
      - GROUPS_FILE=/work/default/config/groups
      - STATIC_GROUPS_FILE=/config/groups
      - PASSWD_FILE=/config/passwd
      - INTERNAL_KEY_STORE=/jks/keys/b_qpid.p12
      - INTERNAL_KEY_STORE_PASSWORD=VwlewgXOxNIL
      - INTERNAL_TRUST_STORE=/jks/keys/internal_b.jks
      - INTERNAL_TRUST_STORE_PASSWORD=_I3Vvm7pyM$$P #NOTE actual password only has one dollar sign, but we're using two due to docker-compose's variable substitution
    depends_on:
    - mock-dns-server
    networks:
    - testing_net

  b_routing_configurer:
    #image: eu.gcr.io/nordic-way-aad182cc/routing-configurer-app:${BRANCH_TAG}
    build:
      context: ../routing-configurer-app
    container_name: b_routing_configurer
    depends_on:
      - b_db
    links:
        - "b_qpid:b.bouvetinterchange.eu"
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://b_db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - BASE_URL=https://b_qpid
      - SERVER_NAME=b.bouvetinterchange.eu
      - TRUST_STORE=/jks/keys/internal_b.jks
      - TRUST_STORE_PASSWORD=_I3Vvm7pyM$$P #Note that the actual password has one dollar sign, but escaped due to variables in docker-compose
      - KEY_STORE=/jks/keys/b_routing_configurer.p12
      - KEY_STORE_PASSWORD=-4U-rAKRymc7
    networks:
    - testing_net

  b_message_collector_app:
    #image: eu.gcr.io/nordic-way-aad182cc/message-collector-app:${BRANCH_TAG}
    build:
      context: ../message-collector-app
    container_name: b_message_collector_app
    depends_on:
      - b_db
    links:
      - "a_qpid:a.bouvetinterchange.eu"
      - "b_qpid:b.bouvetinterchange.eu"
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://b_db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - KEY_STORE=/jks/keys/b.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=FbLeD3NzofRw
      - KEY_STORE_TYPE=PKCS12
      - TRUST_STORE=/jks/keys/ca.bouvetinterchange.eu.jks
      - TRUST_STORE_PASSWORD=ma9+jz78gHHy
      - TRUST_STORE_TYPE=JKS
      - SERVER_NAME=b.bouvetinterchange.eu
    networks:
    - testing_net

networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.28.0.0/16


