version: '3'
services:
  postgis:
    build: ./postgis
    environment:
      - POSTGRES_USER=geolookup
      - POSTGRES_PASSWORD=geolookup
      - POSTGRES_DB=geolookup
    container_name: postgis
    ports:
      - 5432:5432
    volumes:
      - ./logs:/var/log/postgresql

  qpid:
    build: ./qpid
    container_name: qpid
    ports:
      - 8080:8080/tcp
      - 5672:5672/tcp


  filebeat:
    build: ./filebeat
    container_name: filebeat
    volumes:
      - ./logs:/var/log/logfiles
    links:
      - elasticsearch
      - kibana

  elasticsearch:
    image: elasticsearch:${TAG}
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:${TAG}
    container_name: kibana
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - 5601:5601


  logstash:
    build: ./logstash
    container_name: logstash
    links:
    - elasticsearch
    depends_on:
    - elasticsearch
    volumes:
    - ./logstash:/config-dir
    command: logstash -f /config-dir/logstash.conf
    ports:
      - 5044:5044





