version: '3'
services:

# Note: now all the containers are on the same network - testing_net
# An idea for later would be to have two separate networks, one for each node,
# where the modules that need to communicate with each other are a part of both networks.

  mock-dns-server:
    build:
      context: ../fake-dns-server
      dockerfile: dns-dockerfile
    cap_add:
      - NET_ADMIN
    container_name: mock-dns-server
    hostname: mock-dns-server
    networks:
      testing_net:
        ipv4_address: 172.28.1.1
        aliases:
          - dns.bouvetinterchange.eu

  local_db:
    image: postgres:9.6
    container_name: local_db
    depends_on:
      - mock-dns-server
    ports:
      - 5432
    environment:
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - POSTGRES_DB=federation
    networks:
      - testing_net

  local_onboard_server:
    #image: eu.gcr.io/nordic-way-aad182cc/onboard-server-app:${BRANCH_TAG}
    build:
      context: ../onboard-server-app
    container_name: local_onboard_server
    depends_on:
      - local_db
    ports:
      - 32666:8797
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://local_db:5432/federation
      - SERVER_NAME=local.bouvetinterchange.eu
      - DOMAIN_NAME=bouvetinterchange.eu
      - SP_CHNL_PORT=8797
      - TRUST_STORE=/jks/keys/truststore.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/jks/keys/local.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=password
    networks:
      - testing_net


  local_interchange_app:
    #image: eu.gcr.io/nordic-way-aad182cc/interchange-node-app:${BRANCH_TAG}
    build:
      context: ../interchange-node-app
    container_name: local_interchange_app
    hostname: local_interchange_app
    links:
      - "local_qpid:local.bouvetinterchange.eu"
    environment:
      AMQP_URI: amqp://local.bouvetinterchange.eu
      AMQP_USER: interchange
      AMQP_PASSWORD: "12345678"
    depends_on:
      - local_qpid
    networks:
      - testing_net

  local_qpid:
    build:
      context: ../qpid
    container_name: local_qpid
    ports:
      - 8666:8080
      - 443
      - 63002:5671
      - 5672
    volumes:
      - "../qpid/local:/config"
      - "../tmp:/jks"
      - "../qpid/messages/local:/work/local/messages"
      - "../tmp/dump:/dump"
    environment:
      - TRUST_STORE=/jks/keys/truststore.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/jks/keys/local.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=password
      - VHOST_FILE=/work/default/config/default.json
      - STATIC_VHOST_FILE=/config/vhost.json
      - GROUPS_FILE=/work/default/config/groups
      - STATIC_GROUPS_FILE=/config/groups
      - PASSWD_FILE=/config/passwd
      - JAVA_OPTS=-XX:HeapDumpPath=/dump/
    depends_on:
      - mock-dns-server
    networks:
      - testing_net

  local_neighbour_server:
    #image: eu.gcr.io/nordic-way-aad182cc/neighbour-server-app:${BRANCH_TAG}
    build:
      context: ../neighbour-server-app
    container_name: local_neighbour_server
    depends_on:
      - local_db
    ports:
      - 8090
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://local_db:5432/federation
      - SERVER_NAME=local.bouvetinterchange.eu
      - DOMAIN_NAME=bouvetinterchange.eu
      - CTRL_CHNL_PORT=8090
      - TRUST_STORE=/jks/keys/truststore.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/jks/keys/local.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=password
    networks:
      - testing_net
    dns: 172.28.1.1

  local_routing_configurer:
    #image: eu.gcr.io/nordic-way-aad182cc/routing-configurer-app:${BRANCH_TAG}
    build:
      context: ../routing-configurer-app
    container_name: local_routing_configurer
    depends_on:
      - local_db
    links:
      - "local_qpid:local.bouvetinterchange.eu"
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://local_db:5432/federation
      - BASE_URL=https://local.bouvetinterchange.eu
      - SERVER_NAME=local.bouvetinterchange.eu
      - TRUST_STORE=/jks/keys/truststore.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/jks/keys/local.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=password
    networks:
      - testing_net

  local_message_collector_app:
    #image: eu.gcr.io/nordic-way-aad182cc/message-collector-app:${BRANCH_TAG}
    build:
      context: ../message-collector-app
    container_name: local_message_collector_app
    depends_on:
      - local_db
    links:
      - "local_qpid:local.bouvetinterchange.eu"
    volumes:
      - "../tmp:/jks"
    environment:
      - POSTGRES_URI=jdbc:postgresql://local_db:5432/federation
      - KEY_STORE=/jks/keys/local.bouvetinterchange.eu.p12
      - KEY_STORE_PASSWORD=password
      - KEY_STORE_TYPE=PKCS12
      - TRUST_STORE=/jks/keys/truststore.jks
      - TRUST_STORE_PASSWORD=password
      - TRUST_STORE_TYPE=JKS
      - SERVER_NAME=local.bouvetinterchange.eu
    networks:
      - testing_net

networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.28.1.0/16


