apiVersion: batch/v1
kind: Job
metadata:
  name: db-export-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: export
          image: export-service:v2
          args: ["export", "/backup/export.json" ]
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-db:5432/federation
            - name: SPRING_DATASOURCE_USERNAME
              value: federation
            - name: SPRING_DATASOURCE_PASSWORD
              value: federation
          volumeMounts:
            - name: db-backup
              mountPath: /backup
      volumes:
        - name: db-backup
          persistentVolumeClaim:
            claimName: db-backup-pvc