version: '3'
services:
  postgis:
    build: ./postgis
    environment:
      - POSTGRES_USER=geolookup
      - POSTGRES_PASSWORD=geolookup
      - POSTGRES_DB=geolookup
    container_name: postgis
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "geolookup"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
    - "5432"

  qpid-cpp:
    image: scholzj/qpid-cpp
    container_name: qpid-cpp
    hostname: qpid-cpp
    environment:
      - QPIDD_ADMIN_USERNAME=admin
      - QPIDD_ADMIN_PASSWORD=admin
    expose:
    - "5672"

  qpid-gui:
    image: scholzj/qpid-cpp-gui
    container_name: qpid-gui
    environment:
      - QMF_GUI_ADMIN_USERNAME=admin
      - QMF_GUI_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080

  proxy:
    image: nginx:latest
    expose: ["5672"]
    volumes: ["./nginx.conf:/etc/nginx/nginx.conf"]
    hostname: proxy
    container_name: proxy
    ports:
      - 5672:5672

  interchangeapp:
    build: ./interchangeapp
    container_name: interchangeapp
