#load_module /usr/lib/nginx/modules/ngx_stream_module.so;
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
  worker_connections 1024;
}

stream {
  server {
    listen 5672;
    proxy_pass qpid-cpp:5672;
  }
}