version: '3'
services:
  postgis:
    build: ./postgis
    environment:
      - POSTGRES_USER=geolookup
      - POSTGRES_PASSWORD=geolookup
      - POSTGRES_DB=geolookup
    container_name: postgis
    ports:
      - 5432:5432
    volumes:
      - ./logs:/var/log/postgresql


  filebeat:
    image: docker.elastic.co/beats/filebeat:${TAG}
    container_name: filebeat
    volumes:
      - ./logs:/var/log/logfiles
    networks:
      - elknet
    links:
      - elasticsearch
      - kibana

  elasticsearch:
    image: elasticsearch:${TAG}
    container_name: elasticsearch
    networks:
      - elknet
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:${TAG}
    container_name: kibana
    networks:
      - elknet
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - 5601:5601


  logstash:
    build: ./logstash
    container_name: logstash
    links:
    - elasticsearch
    depends_on:
    - elasticsearch
    networks:
    - elknet
    volumes:
    - ./logstash:/config-dir
    command: logstash -f /config-dir/logstash.conf
    ports:
      - 5044:5044
    environment:
      - LOG_LEVEL=debug


networks:
  elknet:
    driver: bridge




