resource_types:
- name: concourse-pipeline
  type: docker-image
  source:
    repository: concourse/concourse-pipeline-resource

resources:
- name: concourse
  type: concourse-pipeline
  source:
    target: https://concourse.t16r.duckdns.org
    teams:
    - name: nordic-way
      username: ((common.concourse-user))
      password: ((common.concourse-pass))

- name: source
  type: git
  source:
    uri: git@github.com:NordicWayInterchange/interchange.git
    private_key: ((common.git-key))

- name: ci-config
  type: git
  source:
    uri: git@github.com:NordicWayInterchange/interchange.git
    private_key: ((common.git-key))
    paths: [ci]

- name: interchangenode
  type: git
  source:
    uri: git@github.com:NordicWayInterchange/interchange.git
    private_key: ((common.git-key))
    paths: [interchangenode]

- name: qpid
  type: git
  source:
    uri: git@github.com:NordicWayInterchange/interchange.git
    private_key: ((common.git-key))
    paths: [qpid]

- name: postgis
  type: git
  source:
    uri: git@github.com:NordicWayInterchange/interchange.git
    private_key: ((common.git-key))
    paths: [postgis]

- name: interchangenode-image
  type: docker-image
  source:
    repository: eu.gcr.io/nordic-way-aad182cc/interchangenode
    username: ((common.gcr-user))
    password: ((common.gcr-pass))

- name: qpid-image
  type: docker-image
  source:
    repository: eu.gcr.io/nordic-way-aad182cc/qpid
    username: ((common.gcr-user))
    password: ((common.gcr-pass))

- name: postgis-image
  type: docker-image
  source:
    repository: eu.gcr.io/nordic-way-aad182cc/postgis
    username: ((common.gcr-user))
    password: ((common.gcr-pass))

jobs:
- name: update-pipeline
  plan:
  - get: source
  - get: ci-config
    trigger: true
  - put: concourse
    params:
      pipelines:
      - name: interchange
        team: nordic-way
        config_file: source/ci/pipeline.yml

- name: build-interchangenode
  plan:
  - get: source
  - get: concourse
    trigger: true
    passed: [update-pipeline]
  - get: interchangenode
    trigger: true
  - task: generate-tag
    config:
      platform: linux
      image_resource: {type: docker-image, source: {repository: alpine/git}}
      inputs: [name: source]
      outputs: [name: tags]
      run:
        path: source/ci/generate-tags.sh
  - put: interchangenode-image
    params:
      build: source/interchangenode
      tag_file: tags/hash-tag
      additional_tags: tags/additional-tags

- name: build-qpid
  plan:
  - get: source
  - get: concourse
    trigger: true
    passed: [update-pipeline]
  - get: qpid
    trigger: true
  - task: generate-tag
    config:
      platform: linux
      image_resource: {type: docker-image, source: {repository: alpine/git}}
      inputs: [name: source]
      outputs: [name: tags]
      run:
        path: source/ci/generate-tags.sh
  - put: qpid-image
    params:
      build: source/qpid
      tag_file: tags/hash-tag
      additional_tags: tags/additional-tags

- name: build-postgis
  plan:
  - get: source
  - get: concourse
    trigger: true
    passed: [update-pipeline]
  - get: postgis
    trigger: true
  - task: generate-tag
    config:
      platform: linux
      image_resource: {type: docker-image, source: {repository: alpine/git}}
      inputs: [name: source]
      outputs: [name: tags]
      run:
        path: source/ci/generate-tags.sh
  - put: postgis-image
    params:
      build: source/postgis
      tag_file: tags/hash-tag
      additional_tags: tags/additional-tags

