services:

  #This DNS server mocks the SRV records for a_interchangedomain.com
  mock-dns-server:
    build:
      context: ./
      dockerfile: dns-single-node-dockerfile
    cap_add:
    - NET_ADMIN
    container_name: mock-dns-server
    hostname: mock-dns-server
    networks:
      singletest:
        ipv4_address: 172.29.1.1
        aliases:
          - dns.lookupdomain.com

  a-db:
    image: postgres:15.1
    depends_on:
      - mock-dns-server
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - POSTGRES_DB=federation
    networks:
    - singletest

  a-onboard-server:
    image: ghcr.io/nordicwayinterchange/onboard-server-app:${IMAGE_TAG}
    depends_on:
      - a-db
    ports:
      - 32666:8797
    volumes:
    - "../keys/a:/keys"
    environment:
      - POSTGRES_URI=jdbc:postgresql://a-db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - SERVER_NAME=a.interchangedomain.com
      - DOMAIN_NAME=lookupdomain.com
      - SP_CHNL_PORT=8797
      - TRUST_STORE=/keys/ca.a.interchangedomain.com.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/keys/a.interchangedomain.com.p12
      - KEY_STORE_PASSWORD=password
    networks:
      - singletest

  a-qpid:
    image: ghcr.io/nordicwayinterchange/qpid:${IMAGE_TAG}
    ports:
      - 8666:8080
      - 443
      - 6003:5671
      - 5672
    volumes:
      - "../qpid/a/config:/config"
      - "../keys/a:/keys"
      - "../qpid/a/messages:/work/a/messages"
    environment:
      - TRUST_STORE=/keys/ca.interchangedomain.com.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/keys/a.qpid.interchangedomain.com.p12
      - KEY_STORE_PASSWORD=password
      - INTERNAL_KEY_STORE=/keys/a-qpid.p12
      - INTERNAL_KEY_STORE_PASSWORD=password
      - VHOST_FILE=/work/default/config/default.json
      - STATIC_VHOST_FILE=/config/vhost.json
      - GROUPS_FILE=/work/default/config/groups
      - STATIC_GROUPS_FILE=/config/groups
      - PASSWD_FILE=/config/passwd
    depends_on:
    - mock-dns-server
    networks:
    - singletest

  a-neighbour-server:
    image: ghcr.io/nordicwayinterchange/neighbour-server-app:${IMAGE_TAG}
    depends_on:
      - a-db
    ports:
      - 8090
    volumes:
      - "../keys/a:/keys"
    environment:
      - POSTGRES_URI=jdbc:postgresql://a-db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - SERVER_NAME=a.interchangedomain.com
      - DOMAIN_NAME=lookupdomain.com
      - CTRL_CHNL_PORT=8090
      - TRUST_STORE=/keys/ca.interchangedomain.com.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/keys/a.interchangedomain.com.p12
      - KEY_STORE_PASSWORD=password
    networks:
    - singletest
    dns: 172.28.1.1

  a-routing-configurer:
    image: ghcr.io/nordicwayinterchange/routing-configurer-app:${IMAGE_TAG}
    depends_on:
      - a-db
    links:
      - "a-qpid:a.interchangedomain.com"
    volumes:
      - "../keys/a:/keys"
    environment:
      - POSTGRES_URI=jdbc:postgresql://a-db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - BASE_URL=https://a-qpid
      - SERVER_NAME=a.interchangedomain.com
      - TRUST_STORE=/keys/ca.interchangedomain.com.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/keys/a.interchangedomain.com.p12
      - KEY_STORE_PASSWORD=password
      - BROKER_EXTERNAL_NAME=a.qpid.interchangedomain.com
    networks:
    - singletest

  a-neighbour-discoverer:
    image: ghcr.io/nordicwayinterchange/neighbour-discoverer-app:${IMAGE_TAG}
    depends_on:
      - a-db
    volumes:
      - "../keys/a:/keys"
    environment:
      - POSTGRES_URI=jdbc:postgresql://a-db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - SERVER_NAME=a.interchangedomain.com
      - DOMAIN_NAME=lookupdomain.com
      - CTRL_CHNL_PORT=8090
      - TRUST_STORE=/keys/ca.interchangedomain.com.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/keys/a.interchangedomain.com.p12
      - KEY_STORE_PASSWORD=password
      - BROKER_EXTERNAL_NAME=a.qpid.interchangedomain.com
    dns: 172.29.1.1
    networks:
    - singletest

  a-message-collector-app:
    image: ghcr.io/nordicwayinterchange/message-collector-app:${IMAGE_TAG}
    depends_on:
    - a-db
    links:
    - "a-qpid:a.qpid.interchangedomain.com"
    volumes:
    - "../keys/a:/keys"
    environment:
    - POSTGRES_URI=jdbc:postgresql://a-db:5432/federation
    - POSTGRES_USER=federation
    - POSTGRES_PASSWORD=federation
    - KEY_STORE=/keys/a.interchangedomain.com.p12
    - KEY_STORE_PASSWORD=password
    - KEY_STORE_TYPE=PKCS12
    - TRUST_STORE=/keys/ca.interchangedomain.com.jks
    - TRUST_STORE_PASSWORD=password
    - TRUST_STORE_TYPE=JKS
    - SERVER_NAME=a.interchangedomain.com
    - BROKER_EXTERNAL_NAME=a.qpid.interchangedomain.com
    networks:
    - singletest
    
  a-napcore-server:
    image: ghcr.io/nordicwayinterchange/napcore-server-app:${IMAGE_TAG}
    depends_on:
      - a-db
    ports:
      - 32777:8898
    volumes:
      - "../keys/a:/keys"
    environment:
      - POSTGRES_URI=jdbc:postgresql://a-db:5432/federation
      - POSTGRES_USER=federation
      - POSTGRES_PASSWORD=federation
      - SERVER_NAME=a.interchangedomain.com
      - NAP_NAME=nap.a.interchangedomain.com
      - DOMAIN_NAME=interchangedomain.com
      - NAP_CHNL_PORT=8898
      - TRUST_STORE=/keys/ca.interchangedomain.com.jks
      - TRUST_STORE_PASSWORD=password
      - KEY_STORE=/keys/a.interchangedomain.com.p12
      - KEY_STORE_PASSWORD=password
      - SIGN_STORE=/keys/ca.a.interchangedomain.com.p12
      - SIGN_STORE_PASSWORD=password
      - SIGN_STORE_ALIAS=ca.a.interchangedomain.com
      - BROKER_EXTERNAL_NAME=a.qpid.interchangedomain.com
    networks:
      - singletest

  a-napcore-frontend:
    image: ghcr.io/nordicwayinterchange/napcore-frontend:${NAP_TAG}
    ports:
      - 3000:3000
    volumes:
      - ../keys/a/nap.a.interchangedomain.com.p12:/app/nap.a.interchangedomain.com.p12
    environment:
      - PFX_KEY_FILENAME=/nap.a.interchangedomain.com.p12
      - PFX_PASSPHRASE=password
      - INTERCHANGE_URI=https://a-napcore-server:8898/nap/
      - INTERCHANGE_PREFIX=a.interchangedomain.lookupdomain.
      - NEXTAUTH_SECRET=supersecret
      - KEYCLOAK_CLIENT_ID=a.interchangedomain.com
      - INTERNAL_KEYCLOAK_URL=http://a-keycloak:8080
      - KEYCLOAK_REALM=a.interchangedomain.com
      - KEYCLOAK_CLIENT_SECRET=anothersupersecret
      - EXTERNAL_KEYCLOAK_URL=http://localhost:8888
    networks:
      - singletest

  a-keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    ports:
      - 8888:8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    # TODO create a realm, export, and use the exported realm in the import part below
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    command: ["start-dev", "--import-realm"]
    networks:
      - singletest

networks:
  singletest:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16

