logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%-13.13thread] %-5level %logger{36}  - %msg%n
logging.level.root=info
spring.output.ansi.enabled=ALWAYS

serverstub.selector = publicationId = 'N00001:1234' and causeCode = 6
serverstub.neighbourname = neighbour
serverstub.hostname = "myhost"
serverstub.queue = "test-queue"
server.port=8090
server.ssl.client-auth=need
