name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven and run integration tests
        run: mvn verify -Dorg.slf4j.simpleLogger.log.org.apache.maven=warn -B
        # Step that does cache save and restore
      - name: Save and restore cache
        id: maven-cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Persist to workspace
        uses: actions/upload-artifact@v2
        with:
          name: interchange
          path: ./*

  docker-push-svv:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: bash
    steps:
      - name: Download persisted wokspace
        uses: actions/download-artifact@v2
        with:
          name: interchange
      - name: Authenticate
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: nw-shared-w3ml
          service_account_key: ${{ secrets.SVV_GITHUB_ACTIONS_PUBLISHER_KEY  }}
      - name: Setup docker
        run: gcloud auth configure-docker
      - name: Build and upload Docker images
        run: chmod +x build-push-images.sh && ./build-push-images.sh eu.gcr.io/nw-shared-w3ml

  helm-package-charts:
    runs-on: ubuntu-latest
    needs: docker-push-svv
    defaults:
      run:
        shell: bash
    steps:
      - name: Download persisted wokspace
        uses: actions/download-artifact@v2
        with:
          name: interchange
      - name: Setup helm
        uses: azure/setup-helm@v1
      - name: Package charts
        run: |
          helm package interchange/helm/interchange -d interchange/target/helm
          helm package interchange/helm/basic-interchange -d interchange/target/helm
          helm repo index interchange/target/helm
      - name: Authenticate
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: nw-shared-w3ml
          ervice_account_key: ${{ secrets.SVV_GITHUB_ACTIONS_PUBLISHER_KEY  }}
      - name: Publish charts
        run: |
          gsutil cp -r interchange/target/helm/ gs://nordic_way_helm_repository