name: Build and Push Docker Images

on:
  push:
  workflow_dispatch:
    inputs:
      git-ref:
        required: false
        description: 'Specified commit hash or branch name (Optional)'

jobs:
  validate-helm-chart:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout (Latest)
        uses: actions/checkout@v3
        if: github.event.inputs.git-ref == ''
      - name: Checkout (Custom commit or branch)
        uses: actions/checkout@v3
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: Setup helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Templating Interchange helm chart
        working-directory: ./helm/interchange
        run: |
          helm template -f example_values.yml .

  build:
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout (Latest)
        uses: actions/checkout@v3
        if: github.event.inputs.git-ref == ''
      - name: Checkout (Custom commit or branch)
        uses: actions/checkout@v3
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven and run integration tests
        run: mvn verify -Dorg.slf4j.simpleLogger.log.org.apache.maven=warn
        # Step that does cache save and restore
      - name: Save and restore cache
        id: maven-cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Persist to workspace
        uses: actions/upload-artifact@v3
        with:
          name: interchange
          path: ./

  docker-push-svv:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: bash
    steps:
      - name: Download persisted workspace
        uses: actions/download-artifact@v3
        with:
          name: interchange
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.SVV_GITHUB_ACTIONS_PUBLISHER_KEY  }}
      - name: Setup docker
        run: gcloud auth configure-docker
      - name: Build and upload Docker images
        run: chmod +x build-push-images.sh && ./build-push-images.sh eu.gcr.io/nw-shared-w3ml
