name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven and run integration tests
        run: mvn package -Dorg.slf4j.simpleLogger.log.org.apache.maven=warn -B
        # Step that does cache save and restore
      - name: Save and restore cache
        id: maven-cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Persist to workspace
        uses: actions/upload-artifact@v2
        with:
          name: interchange
          path: ./*

  maven-deploy:
    runs-on: ubuntu-latest

    needs: build

    defaults:
      run:
        shell: bash

    steps:
      - name: Download persisted wokspace
        uses: actions/download-artifact@v2
        with:
          name: interchange
      - name: Authenticate
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.BOUVET_PROJECT_ID }}
          service_account_key: ${{ secrets.BOUVET_GITHUB_ACTIONS  }}
      - name: Test
        run: gcloud info

      - name: Indicate success
        run: echo Success
