name: Docker Image CI

permissions:
  contents: read
  id-token: write

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Artifact Registry
        run: gcloud auth configure-docker ${{ vars.REGIONAL_ARTIFACT_REGISTRY_URL }} --quiet

      - name: Create tag
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: Build the Docker image
        run: docker build . -t admin-frontend --file Dockerfile

      - name: Push docker image to Github container registry
        run: |
          docker tag admin-frontend ghcr.io/nordicwayinterchange/admin-frontend:${{ env.IMAGE_TAG }}
          docker push --all-tags ghcr.io/nordicwayinterchange/admin-frontend