name: Push Helm Charts

on:
  push:
    branches:
      - federation-master
  workflow_dispatch:
    inputs:
      git-ref:
        required: false
        description: 'Specified commit hash or branch name (Optional)'

jobs:
  helm-package-charts:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout (Latest)
        uses: actions/checkout@v3
        if: github.event.inputs.git-ref == ''
      - name: Checkout (Custom commit or branch)
        uses: actions/checkout@v3
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: Setup helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Package charts
        run: |
          helm package helm/interchange -d target/helm
          helm package helm/basic-interchange -d target/helm
          helm repo index target/helm
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.SVV_GITHUB_ACTIONS_PUBLISHER_KEY  }}
      - id: upload-file
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: target/helm/
          destination: nordic_way_helm_repository
          parent: false