name: Release

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
    inputs:
      git-ref:
        required: false
        description: 'Specified commit hash or branch name'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout (Latest)
        uses: actions/checkout@v4
        if: github.event.inputs.git-ref == ''
      - name: Checkout (Custom commit or branch)
        uses: actions/checkout@v4
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

#      - name: Create settings file
#        run:  |
#          cat << EOF > ~/.m2/settings.xml
#          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
#          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
#          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
#          http://maven.apache.org/xsd/settings-1.0.0.xsd">
#
#          <activeProfiles>
#          <activeProfile>github</activeProfile>
#          </activeProfiles>
#
#          <profiles>
#          <profile>
#          <id>github</id>
#          <repositories>
#          <repository>
#          <id>central</id>
#          <url>https://repo1.maven.org/maven2</url>
#          </repository>
#          <repository>
#          <id>github</id>
#          <url>https://maven.pkg.github.com/NordicWayInterchange/interchange</url>
#          <snapshots>
#          <enabled>true</enabled>
#          </snapshots>
#          </repository>
#          </repositories>
#          </profile>
#          </profiles>
#
#          <servers>
#          <server>
#          <id>github</id>
#          <username>Github.Actions</username>
#          <password>${{ secrets.REPO_ACCESS_TOKEN }}</password>
#          </server>
#          </servers>
#          </settings>
#          EOF
#
      - name: Save version for release
        run: |
          echo "CURRENT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/[^0-9.]//g')-TEST" >> "$GITHUB_ENV"
          echo "$(mvn org.apache.maven.plugins:maven-help-plugin:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/[^0-9.]//g')-TEST" >> CURRENT_VERSION.txt
#
#      - name: Git config for maven-release-plugin
#        run: |
#          git config user.email "github@actions.github.com"
#          git config user.name "Github Actions"
#
#      - name: Prepare release
#        run: |
#          mvn -B -Darguments=-DskipTests release:clean release:prepare -Dtag=${{ env.CURRENT_VERSION }}
#
#      - name: Perform release
#        run: |
#          mvn -B release:perform
#
#      - name: Create release in Github
#        uses: ncipollo/release-action@v1
#        with:
#          tag: ${{ env.CURRENT_VERSION }}
#          token: ${{ secrets.GITHUB_TOKEN }}
#          name: ${{ env.CURRENT_VERSION }}
#          makeLatest: true
#          draft: false
#          prerelease: false
#
#      - name: Persist to workspace
#        uses: actions/upload-artifact@v4
#        with:
#          name: interchange
#          path: ./
#
  build-napcore:
    runs-on: ubuntu-latest
    needs: release
    defaults:
      run:
        shell: bash
    steps:
      - name: Download persisted workspace
        uses: actions/download-artifact@v4
        with:
          name: interchange
      - name: Tags to variables
        run: |
          echo "CURRENT_VERSION=$(cat CURRENT_VERSION.txt)" >> "$GITHUB_ENV"
      - name: Login to Github container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: "Github Actions"
          password: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Build the Docker image
        run: |
          cd ./frontend
          docker build . -t napcore-frontend
      - name: Push docker image to Github container registry
        run: |
          docker tag napcore-frontend ghcr.io/nordicwayinterchange/napcore-frontend:${{ env.CURRENT_VERSION }}
          docker push --all-tags ghcr.io/nordicwayinterchange/napcore-frontend


 # docker-push-svv:
 #   runs-on: ubuntu-latest
 #   needs: release
 #   strategy:
 #     matrix:
 #       Images: [message-collector-app,neighbour-discoverer-app,neighbour-server-app,routing-configurer-app,onboard-server-app,napcore-server-app,service-provider-client,keys-generator, admin-server-app]
 #   defaults:
 #     run:
 #       shell: bash
 #   steps:
 #     - name: Download persisted workspace
 #       uses: actions/download-artifact@v4
 #       with:
 #         name: interchange
#
#      - name: Save version number to variable
#        run: |
#          echo "CURRENT_VERSION=$(cat CURRENT_VERSION.txt)" >> "$GITHUB_ENV"
#
#      - name: Build the Docker image
#        run: |
#          cd ./${{ matrix.Images }}
#          docker build . -t ${{ matrix.Images }} --build-arg JAR_VERSION=${{ env.CURRENT_VERSION }}
#
#      - name: Login to Github container registry
#        uses: docker/login-action@v3.3.0
#        with:
#          registry: ghcr.io
#          username: "Github Actions"
#          password: ${{ secrets.REPO_ACCESS_TOKEN }}
#
#      - name: Push docker image to Github container registry
#        run: |
#          docker tag ${{ matrix.Images }} ghcr.io/nordicwayinterchange/${{ matrix.Images }}:${{ env.CURRENT_VERSION }}
#          docker push --all-tags ghcr.io/nordicwayinterchange/${{ matrix.Images }}
#