FROM java:8-alpine
RUN apk add --no-cache bash

COPY target/jms-client-1.0.3-SNAPSHOT.jar jms-client.jar
COPY src/main/resources/sink.properties sink.properties
ENTRYPOINT ["java","-cp","jms-client.jar","no.vegvesen.ixn.Sink","sink.properties"]
#ENTRYPOINT "/bin/bash"
